#!/usr/bin/env python3
"""Generate the typed Swift tutor procedure catalog from the reviewed artifact.

The reviewed JSON artifact is the human-auditable source of truth. The
generated Swift embeds the exact JSON payload plus its SHA-256 so runtime
loading fails closed if either side drifts. Run the audit script for the deep
rule validation; this generator performs structural checks only.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_INPUT = ROOT / "research/knowledge/logic-pro-12.3-tutor-procedures.json"
DEFAULT_OUTPUT = (
    ROOT
    / "packages/ProductionTutor/Sources/ProductionTutor/TutorProcedureKnowledge.generated.swift"
)
EXPECTED_SCHEMA = "tracksmith.logic-tutor-procedures.v1"

TEMPLATE = '''// Generated by research/scripts/build-logic-tutor-procedure-knowledge.py
// from {relative_input}.
// Do not edit by hand. Regenerate with:
//   python3 research/scripts/build-logic-tutor-procedure-knowledge.py
// The runtime loader verifies the embedded payload against the recorded
// SHA-256 and then runs TutorKnowledgeValidator before any procedure is used.

public enum TutorProcedureKnowledgeGenerated {{
    public static let sourceArtifactPath = "{relative_input}"
    public static let sourceArtifactSHA256 = "{sha256}"
    public static let procedureCount = {procedure_count}
    public static let catalogJSON = #"""
{payload}
"""#
}}
'''


def build(payload_text: str, relative_input: str, procedure_count: int) -> str:
    digest = hashlib.sha256(payload_text.encode("utf-8")).hexdigest()
    return TEMPLATE.format(
        relative_input=relative_input,
        sha256=digest,
        procedure_count=procedure_count,
        payload=payload_text,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=pathlib.Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()

    payload_text = args.input.read_text(encoding="utf-8")
    # The payload is embedded verbatim inside a Swift raw string literal, so it
    # must not contain the closing delimiter.
    if '"""#' in payload_text:
        print("ERROR: payload contains the Swift raw-string delimiter", file=sys.stderr)
        return 1
    catalog = json.loads(payload_text)
    if catalog.get("schemaVersion") != EXPECTED_SCHEMA:
        print(f"ERROR: unexpected schemaVersion {catalog.get('schemaVersion')!r}", file=sys.stderr)
        return 1
    procedures = catalog.get("procedures", [])
    if not procedures:
        print("ERROR: empty procedure catalog", file=sys.stderr)
        return 1

    relative_input = str(args.input.resolve().relative_to(ROOT))
    generated = build(payload_text, relative_input, len(procedures))

    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != generated:
            print("TUTOR_PROCEDURE_GENERATED_CHECK_FAILED: regenerate the Swift catalog")
            return 1
        print(f"TUTOR_PROCEDURE_GENERATED_CHECK_OK procedures={len(procedures)}")
        return 0

    args.output.write_text(generated, encoding="utf-8")
    print(f"WROTE {args.output} procedures={len(procedures)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
