// swift-tools-version: 6.1
import PackageDescription

let package = Package(
    name: "LogicAudioAssistant",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "CAtomics", targets: ["CAtomics"]),
        .library(name: "PlanSchema", targets: ["PlanSchema"]),
        .library(name: "DSPCore", targets: ["DSPCore"]),
        .library(name: "AudioAnalysis", targets: ["AudioAnalysis"]),
        .library(name: "StateStore", targets: ["StateStore"]),
        .library(name: "AgentCore", targets: ["AgentCore"]),
        .library(name: "PreviewRenderer", targets: ["PreviewRenderer"]),
        .library(name: "PreviewWorkflow", targets: ["PreviewWorkflow"]),
        .library(name: "LogicBridge", targets: ["LogicBridge"]),
        .library(name: "SharedIPC", targets: ["SharedIPC"]),
        .library(name: "AudioUnitExtensionCore", targets: ["AudioUnitExtensionCore"]),
        .executable(name: "CompanionApp", targets: ["CompanionApp"]),
        .executable(name: "OfflineRenderer", targets: ["OfflineRenderer"]),
        .executable(name: "AnalysisCLI", targets: ["AnalysisCLI"]),
        .executable(name: "LogicIntegrationProbe", targets: ["LogicIntegrationProbe"]),
        .executable(name: "PluginProbe", targets: ["PluginProbe"]),
        .executable(name: "AudioUnitHostProbe", targets: ["AudioUnitHostProbe"]),
        .executable(name: "PreviewCLI", targets: ["PreviewCLI"]),
        .executable(name: "AuditionApp", targets: ["AuditionApp"]),
        .executable(name: "TestSignalGenerator", targets: ["TestSignalGenerator"]),
        .executable(name: "TestRunner", targets: ["TestRunner"]),
    ],
    targets: [
        .target(name: "CAtomics", path: "packages/CAtomics", publicHeadersPath: "include"),
        .target(name: "PlanSchema", path: "packages/PlanSchema/Sources/PlanSchema"),
        .target(name: "DSPCore", dependencies: ["PlanSchema"], path: "packages/DSPCore/Sources/DSPCore"),
        .target(name: "AudioAnalysis", dependencies: ["DSPCore", "CAtomics"], path: "packages/AudioAnalysis/Sources/AudioAnalysis"),
        .target(name: "StateStore", dependencies: ["PlanSchema"], path: "packages/StateStore/Sources/StateStore"),
        .target(name: "AgentCore", dependencies: ["PlanSchema", "AudioAnalysis", "StateStore"], path: "packages/AgentCore/Sources/AgentCore"),
        .target(name: "PreviewRenderer", dependencies: ["PlanSchema", "DSPCore", "AudioAnalysis"], path: "packages/PreviewRenderer/Sources/PreviewRenderer"),
        .target(name: "PreviewWorkflow", dependencies: ["AgentCore", "PreviewRenderer", "PlanSchema", "DSPCore", "AudioAnalysis"], path: "packages/PreviewWorkflow/Sources/PreviewWorkflow"),
        .target(name: "LogicBridge", dependencies: ["PlanSchema"], path: "packages/LogicBridge/Sources/LogicBridge"),
        .target(name: "SharedIPC", dependencies: ["PlanSchema"], path: "packages/SharedIPC/Sources/SharedIPC"),
        .target(
            name: "AudioUnitExtensionCore",
            dependencies: ["AudioAnalysis", "CAtomics", "DSPCore", "PlanSchema"],
            path: "plugins/AudioUnit/AudioUnitExtension",
            exclude: [
                "AssistantAudioUnitExtension.entitlements",
                "AudioUnitViewController.swift",
                "Info.plist",
            ]
        ),
        .executableTarget(name: "CompanionApp", dependencies: ["AgentCore", "PreviewRenderer", "SharedIPC", "DSPCore", "AudioAnalysis", "PlanSchema"], path: "apps/CompanionApp/Sources/CompanionApp"),
        .executableTarget(name: "OfflineRenderer", dependencies: ["DSPCore", "PlanSchema", "AudioAnalysis"], path: "tools/OfflineRenderer/Sources/OfflineRenderer"),
        .executableTarget(name: "AnalysisCLI", dependencies: ["AudioAnalysis", "DSPCore"], path: "tools/AnalysisCLI/Sources/AnalysisCLI"),
        .executableTarget(name: "LogicIntegrationProbe", dependencies: ["LogicBridge"], path: "tools/LogicIntegrationProbe/Sources/LogicIntegrationProbe"),
        .executableTarget(name: "PluginProbe", dependencies: ["SharedIPC"], path: "tools/PluginProbe/Sources/PluginProbe"),
        .executableTarget(name: "AudioUnitHostProbe", dependencies: ["AudioUnitExtensionCore", "PlanSchema"], path: "tools/AudioUnitHostProbe/Sources/AudioUnitHostProbe"),
        .executableTarget(name: "PreviewCLI", dependencies: ["PreviewWorkflow", "PlanSchema"], path: "tools/PreviewCLI/Sources/PreviewCLI"),
        .executableTarget(name: "AuditionApp", dependencies: ["PreviewWorkflow", "DSPCore", "PlanSchema"], path: "tools/AuditionApp/Sources/AuditionApp"),
        .executableTarget(name: "TestSignalGenerator", dependencies: ["DSPCore"], path: "tools/TestSignalGenerator/Sources/TestSignalGenerator"),
        .executableTarget(name: "TestRunner", dependencies: ["PlanSchema", "DSPCore", "AudioAnalysis", "StateStore", "AgentCore", "PreviewRenderer", "PreviewWorkflow", "SharedIPC"], path: "tests/TestRunner"),
    ]
)
