// Generated by research/scripts/build-logic-tutor-procedure-knowledge.py
// from research/knowledge/logic-pro-12.3-tutor-procedures.json.
// Do not edit by hand. Regenerate with:
//   python3 research/scripts/build-logic-tutor-procedure-knowledge.py
// The runtime loader verifies the embedded payload against the recorded
// SHA-256 and then runs TutorKnowledgeValidator before any procedure is used.

public enum TutorProcedureKnowledgeGenerated {
    public static let sourceArtifactPath = "research/knowledge/logic-pro-12.3-tutor-procedures.json"
    public static let sourceArtifactSHA256 = "38bf98a1ea163f015257e5d2a5ef19f5b4837ff43119d9a21aca41e1c0a9c702"
    public static let procedureCount = 8
    public static let catalogJSON = #"""
{
  "schemaVersion": "tracksmith.logic-tutor-procedures.v1",
  "logicVersion": "12.3",
  "reviewedAt": "2026-08-05",
  "reviewNotes": "Reviewed against the Logic Pro 12.3 documentary atlases and the accepted G2 bounded empirical profiles. Navigation is semantic and version-scoped; pixel coordinates and key commands are prohibited. Numeric bounds are professional-practice heuristics with explicit stop rules, not universal targets. No procedure grants TrackSmith any execution authority over Logic; every step is performed by the user.",
  "recognizedProcessorIdentities": [
    "logic-pro-12.3:channel-eq",
    "logic-pro-12.3:compressor",
    "logic-pro-12.3:deesser-2",
    "logic-pro-12.3:noise-gate",
    "logic-pro-12.3:chromaverb",
    "logic-pro-12.3:space-designer",
    "logic-pro-12.3:stereo-delay",
    "logic-pro-12.3:tape-delay"
  ],
  "procedures": [
    {
      "id": "tutor.vocal.compression-emphasis-check.v1",
      "version": "1.0",
      "logicVersionScope": "logic-pro-12.3",
      "supportedSourceTypes": ["vocal", "vocalBus"],
      "supportedIssues": ["nasalOrHonky", "congested", "harsh", "overcompressed", "boxy"],
      "candidateCauses": ["dynamicsInteraction", "existingProcessing"],
      "prerequisiteQuestions": ["Is a compressor currently active on this vocal channel strip?"],
      "processorIdentities": ["logic-pro-12.3:compressor"],
      "entryStepID": "tutor.vocal.compression-emphasis-check.v1.confirm",
      "steps": [
        {
          "id": "tutor.vocal.compression-emphasis-check.v1.confirm",
          "procedureID": "tutor.vocal.compression-emphasis-check.v1",
          "actionKind": "inspectOrConfirmCurrentState",
          "actor": "userManual",
          "title": "Find the compressor on the vocal channel strip",
          "instruction": "Select the vocal track, then look at its channel strip in the Inspector on the left or in the Mixer. In the Audio FX section, look for a slot named Compressor or another compressor.",
          "substeps": [
            "Click the vocal track header so it is selected.",
            "Look at the channel strip's Audio FX slots.",
            "Note which slot holds the compressor."
          ],
          "reason": "The next experiment bypasses only that compressor, so we first confirm it exists and where it is.",
          "technicalExplanation": "Logic channel strips list insert effects in Audio FX slots in processing order. TrackSmith cannot see your inserts, so your report is the only evidence about what is on this strip.",
          "listenFor": "Nothing yet. This step only confirms what is present.",
          "expectedResult": "You know whether a compressor is active and which slot it is in.",
          "hypothesisWrongSigns": [],
          "preservationChecks": ["Do not remove or reorder any plug-in in this step."],
          "commonSideEffect": "None. This step changes nothing.",
          "stopCondition": "Stop once you can say whether a compressor is present.",
          "undoInstruction": "Nothing to undo. This step changes nothing.",
          "location": {
            "logicVersion": "12.3",
            "workArea": "Inspector channel strip or Mixer",
            "objectScope": "Selected vocal track channel strip",
            "processorIdentity": "logic-pro-12.3:compressor",
            "controlIdentity": "audio-fx-slot",
            "navigationLabels": ["Inspector", "Channel strip", "Audio FX"],
            "requiredFocusOrSelection": "The vocal track must be selected so the Inspector shows its channel strip.",
            "prerequisites": ["The project containing the vocal is open."],
            "verification": "documentary",
            "sourceReferences": [
              "Apple Logic Pro User Guide (channel strips and Audio FX slots)",
              "research/analysis/TRACKSMITH_LOGIC_PRO_12_3_WORKFLOW_ATLAS.md"
            ],
            "lastDirectlyVerified": null
          },
          "parameters": [],
          "supportedFeedback": ["done", "notApplicable", "cannotFindControl"],
          "branches": [
            { "feedback": "done", "nextStepID": "tutor.vocal.compression-emphasis-check.v1.bypass", "effectSummary": "Compressor located; run the bypass experiment." },
            { "feedback": "notApplicable", "nextStepID": null, "effectSummary": "No compressor is in use, so compression cannot be emphasizing the problem; move to the next competing cause." },
            { "feedback": "cannotFindControl", "nextStepID": null, "effectSummary": "Show the navigation card again with prerequisites." }
          ],
          "confidence": 0.6,
          "uncertainty": ["TrackSmith cannot verify your channel strip; this relies on your report."],
          "concepts": ["sourceVersusProcessing"]
        },
        {
          "id": "tutor.vocal.compression-emphasis-check.v1.bypass",
          "procedureID": "tutor.vocal.compression-emphasis-check.v1",
          "actionKind": "bypassProcessor",
          "actor": "userManual",
          "title": "Bypass only the compressor and listen again",
          "instruction": "Bypass just the compressor: move the pointer over its Audio FX slot and click the small power button on the left side of the slot so the slot dims. Then play the same phrase again at about the same listening level.",
          "substeps": [
            "Move the pointer over the compressor slot.",
            "Click the slot's power button so it dims.",
            "Replay the same phrase you were judging."
          ],
          "reason": "A compressor can keep a midrange resonance loud for more of each phrase. Removing it briefly tests one possible cause without changing anything permanently.",
          "technicalExplanation": "Compression reduces the level difference between the strongest and weakest moments. If a resonant quality lives in the sustained part of words, raising that sustain relative to the peaks keeps the quality audible for longer, so it reads as more pinched. This test does not prove compression is the cause; it isolates one possibility.",
          "listenFor": "Does the pinched or honky quality become clearly less obvious with the compressor off? Ignore small loudness differences for now.",
          "expectedResult": "You can say whether the quality is noticeably tied to the compressor being active.",
          "hypothesisWrongSigns": [
            "The quality is just as strong with the compressor off.",
            "Everything only sounds quieter or louder rather than different in character."
          ],
          "preservationChecks": ["Only the compressor is bypassed; no setting inside any plug-in changes."],
          "commonSideEffect": "The vocal will usually get quieter and less even with the compressor off, which can bias your impression. Try to judge the pinched character, not the loudness.",
          "stopCondition": "Stop after two or three replays; longer comparison invites loudness bias.",
          "undoInstruction": "Click the same power button on the compressor slot again so it lights up. That restores exactly the previous state.",
          "location": {
            "logicVersion": "12.3",
            "workArea": "Inspector channel strip or Mixer",
            "objectScope": "Compressor Audio FX slot on the vocal channel strip",
            "processorIdentity": "logic-pro-12.3:compressor",
            "controlIdentity": "audio-fx-slot-power-button",
            "navigationLabels": ["Channel strip", "Audio FX", "slot power button"],
            "requiredFocusOrSelection": "The vocal track's channel strip must be visible.",
            "prerequisites": ["The compressor slot was identified in the previous step."],
            "verification": "documentary",
            "sourceReferences": [
              "Apple Logic Pro User Guide (turn plug-ins on and off in the channel strip)",
              "research/analysis/TRACKSMITH_LOGIC_PRO_12_3_WORKFLOW_ATLAS.md"
            ],
            "lastDirectlyVerified": null
          },
          "parameters": [],
          "supportedFeedback": ["better", "worse", "noChange", "notSure", "cannotFindControl", "undo"],
          "branches": [
            { "feedback": "better", "nextStepID": "tutor.vocal.compression-emphasis-check.v1.gentler", "effectSummary": "Compression involvement strengthened; try a gentler compression setting instead of leaving it off." },
            { "feedback": "worse", "nextStepID": "tutor.vocal.compression-emphasis-check.v1.restore", "effectSummary": "Bypassing made it worse; restore the compressor and mark this branch contraindicated." },
            { "feedback": "noChange", "nextStepID": "tutor.vocal.compression-emphasis-check.v1.restore", "effectSummary": "Compression is probably not the driver; restore it and test the next competing cause." },
            { "feedback": "notSure", "nextStepID": "tutor.vocal.compression-emphasis-check.v1.match", "effectSummary": "Simplify the comparison and control loudness before judging again." },
            { "feedback": "cannotFindControl", "nextStepID": null, "effectSummary": "Show the versioned navigation card and prerequisites." },
            { "feedback": "undo", "nextStepID": "tutor.vocal.compression-emphasis-check.v1.restore", "effectSummary": "Restore the previous state." }
          ],
          "confidence": 0.55,
          "uncertainty": [
            "A loudness drop with the compressor off can mask a genuine improvement or fake one.",
            "The cause may be a combination; one experiment rarely settles it."
          ],
          "concepts": ["dynamicVersusStaticProcessing", "sourceVersusProcessing", "monitoringBias"]
        },
        {
          "id": "tutor.vocal.compression-emphasis-check.v1.match",
          "procedureID": "tutor.vocal.compression-emphasis-check.v1",
          "actionKind": "levelMatchComparison",
          "actor": "userManual",
          "title": "Repeat the comparison at a matched loudness",
          "instruction": "Loop one short phrase of 5 to 15 seconds. Compare compressor on versus off again, but first nudge the channel volume fader while the compressor is off so both versions feel about equally loud. Then judge only the pinched character.",
          "substeps": [
            "Set a cycle range around one phrase.",
            "Toggle the compressor slot power button between passes.",
            "Nudge the fader so both passes feel equally loud.",
            "Judge the character, not the volume."
          ],
          "reason": "Louder almost always sounds better. Matching loudness removes the most common source of a false impression.",
          "technicalExplanation": "Loudness bias is a well-documented perceptual effect: level differences of even 1 dB can change preference judgments. Matching by ear is approximate but far better than ignoring it.",
          "listenFor": "With loudness matched, does the pinched quality still track the compressor state?",
          "expectedResult": "A clearer better/worse/no-change judgment than before.",
          "hypothesisWrongSigns": ["Your judgment flips depending on which version you heard last."],
          "preservationChecks": ["Return the channel volume fader to its original value after the comparison."],
          "commonSideEffect": "Fader moves made for the comparison can linger; note the original value first.",
          "stopCondition": "Stop after a few matched passes. If you still cannot tell, treat the result as no change.",
          "undoInstruction": "Set the channel volume fader back to its noted original value and leave the compressor slot lit.",
          "location": {
            "logicVersion": "12.3",
            "workArea": "Tracks area and channel strip",
            "objectScope": "Cycle range plus vocal channel strip fader and compressor slot",
            "processorIdentity": "logic-pro-12.3:compressor",
            "controlIdentity": "channel-volume-fader",
            "navigationLabels": ["Cycle range", "Channel strip", "Volume fader"],
            "requiredFocusOrSelection": "The vocal track's channel strip must be visible.",
            "prerequisites": ["Note the current fader value before nudging it."],
            "verification": "documentary",
            "sourceReferences": [
              "Apple Logic Pro User Guide (cycle playback; channel strip volume)",
              "research/analysis/TRACKSMITH_LOGIC_PRO_12_3_WORKFLOW_ATLAS.md"
            ],
            "lastDirectlyVerified": null
          },
          "parameters": [],
          "supportedFeedback": ["better", "worse", "noChange", "done", "undo"],
          "branches": [
            { "feedback": "better", "nextStepID": "tutor.vocal.compression-emphasis-check.v1.gentler", "effectSummary": "With loudness matched, compression involvement is strengthened." },
            { "feedback": "worse", "nextStepID": "tutor.vocal.compression-emphasis-check.v1.restore", "effectSummary": "Restore and mark contraindicated." },
            { "feedback": "noChange", "nextStepID": "tutor.vocal.compression-emphasis-check.v1.restore", "effectSummary": "Restore and move to the next competing cause." },
            { "feedback": "done", "nextStepID": "tutor.vocal.compression-emphasis-check.v1.restore", "effectSummary": "Restore the previous state." },
            { "feedback": "undo", "nextStepID": "tutor.vocal.compression-emphasis-check.v1.restore", "effectSummary": "Restore the previous state." }
          ],
          "confidence": 0.6,
          "uncertainty": ["Ear-matched loudness is approximate."],
          "concepts": ["levelMatchedComparison", "monitoringBias", "gain"]
        },
        {
          "id": "tutor.vocal.compression-emphasis-check.v1.gentler",
          "procedureID": "tutor.vocal.compression-emphasis-check.v1",
          "actionKind": "setControl",
          "actor": "userManual",
          "title": "Try gentler compression instead of none",
          "instruction": "Turn the compressor back on, then open it by clicking the middle of its slot. Raise the Threshold a little so the gain-reduction meter shows roughly half of the reduction it showed before, and if Ratio is above about 3 to 1, lower it toward 2 to 1. Replay the phrase.",
          "substeps": [
            "Turn the compressor slot back on and open it.",
            "Note the current Threshold and Ratio values.",
            "Raise Threshold until reduction is roughly halved.",
            "If Ratio is high, lower it toward 2 to 1."
          ],
          "reason": "If strong compression exaggerates the quality, gentler settings may keep the vocal even without emphasizing the resonance.",
          "technicalExplanation": "Threshold sets the level where gain reduction begins; Ratio sets how strongly the level above the threshold is reduced. Less reduction leaves more of the natural difference between the attack and the sustain of each word, so a sustained resonance is boosted less relative to the rest.",
          "listenFor": "Is the vocal still reasonably even, while the pinched quality is less obvious than before?",
          "expectedResult": "A compromise setting that keeps useful evenness with less emphasis on the problem.",
          "hypothesisWrongSigns": ["Any amount of compression brings the quality straight back."],
          "preservationChecks": [
            "Write down the original Threshold and Ratio values before changing them.",
            "Keep the compressor's output or make-up gain where it was so loudness stays comparable."
          ],
          "commonSideEffect": "Less compression means more level variation between words; that trade-off is expected.",
          "stopCondition": "Stop when the quality is acceptable or when two adjustments have not helped.",
          "undoInstruction": "Set Threshold and Ratio back to the values you wrote down, then close the plug-in window.",
          "location": {
            "logicVersion": "12.3",
            "workArea": "Compressor plug-in window",
            "objectScope": "Compressor on the vocal channel strip",
            "processorIdentity": "logic-pro-12.3:compressor",
            "controlIdentity": "threshold-and-ratio",
            "navigationLabels": ["Channel strip", "Audio FX", "Compressor", "Threshold", "Ratio"],
            "requiredFocusOrSelection": "The compressor plug-in window must be open.",
            "prerequisites": ["The compressor slot is on."],
            "verification": "documentary",
            "sourceReferences": [
              "Apple Logic Pro Effects User Guide (Compressor: Threshold, Ratio, gain-reduction meter)",
              "research/analysis/TRACKSMITH_LOGIC_PRO_12_3_TOOL_ATLAS.md"
            ],
            "lastDirectlyVerified": null
          },
          "parameters": [
            {
              "controlIdentity": "compressor-ratio",
              "unit": "ratio",
              "safeStartingValue": 2.0,
              "minimumValue": 1.5,
              "maximumValue": 4.0,
              "enumeratedChoices": [],
              "adjustmentMethod": "steppedAdjustment",
              "sweepDirection": "downward",
              "stepDescription": "Lower Ratio in small steps toward 2 to 1.",
              "stopCondition": "Stop lowering when evenness starts to suffer.",
              "maximumRecommendedExcursion": 2.5,
              "audibleWarningSigns": ["Words start jumping out unevenly."],
              "rollbackValueDescription": "Return Ratio to the value you noted before this step."
            }
          ],
          "supportedFeedback": ["better", "worse", "noChange", "notSure", "undo"],
          "branches": [
            { "feedback": "better", "nextStepID": null, "effectSummary": "Keep the gentler setting; complete the lesson with a summary of what worked." },
            { "feedback": "worse", "nextStepID": "tutor.vocal.compression-emphasis-check.v1.restore", "effectSummary": "Restore the original settings." },
            { "feedback": "noChange", "nextStepID": "tutor.vocal.compression-emphasis-check.v1.restore", "effectSummary": "Restore and test the next competing cause." },
            { "feedback": "notSure", "nextStepID": "tutor.vocal.compression-emphasis-check.v1.match", "effectSummary": "Verify with a loudness-matched comparison." },
            { "feedback": "undo", "nextStepID": "tutor.vocal.compression-emphasis-check.v1.restore", "effectSummary": "Restore the original settings." }
          ],
          "confidence": 0.5,
          "uncertainty": [
            "Compressor behavior depends on the selected model and material; these bounds are practice heuristics, not universal settings."
          ],
          "concepts": ["threshold", "ratio", "makeupGain", "dynamicVersusStaticProcessing"]
        },
        {
          "id": "tutor.vocal.compression-emphasis-check.v1.restore",
          "procedureID": "tutor.vocal.compression-emphasis-check.v1",
          "actionKind": "restorePreviousState",
          "actor": "userManual",
          "title": "Restore the compressor exactly as it was",
          "instruction": "Turn the compressor slot back on if it is off, and return any Threshold or Ratio values you changed to the numbers you wrote down.",
          "substeps": [
            "Click the compressor slot's power button so it lights up.",
            "Reopen the plug-in and restore noted values if you changed any."
          ],
          "reason": "Every experiment must end in a known state so later tests stay trustworthy.",
          "technicalExplanation": "Returning to the exact prior state means the next experiment changes only one variable at a time.",
          "listenFor": "The vocal should sound exactly as it did before this experiment began.",
          "expectedResult": "The channel strip is back to its pre-experiment state.",
          "hypothesisWrongSigns": [],
          "preservationChecks": ["Confirm the slot is lit and values match your notes."],
          "commonSideEffect": "None when the noted values are restored.",
          "stopCondition": "Stop once the state matches your notes.",
          "undoInstruction": "This step is itself the undo. If unsure, use Logic's Undo History for plug-in changes.",
          "location": {
            "logicVersion": "12.3",
            "workArea": "Inspector channel strip or Mixer",
            "objectScope": "Compressor Audio FX slot on the vocal channel strip",
            "processorIdentity": "logic-pro-12.3:compressor",
            "controlIdentity": "audio-fx-slot-power-button",
            "navigationLabels": ["Channel strip", "Audio FX", "slot power button"],
            "requiredFocusOrSelection": "The vocal track's channel strip must be visible.",
            "prerequisites": [],
            "verification": "documentary",
            "sourceReferences": [
              "Apple Logic Pro User Guide (turn plug-ins on and off in the channel strip)"
            ],
            "lastDirectlyVerified": null
          },
          "parameters": [],
          "supportedFeedback": ["done"],
          "branches": [
            { "feedback": "done", "nextStepID": null, "effectSummary": "State restored; the tutor chooses the next experiment or completes." }
          ],
          "confidence": 0.6,
          "uncertainty": [],
          "concepts": ["sourceVersusProcessing"]
        }
      ],
      "preservationRequirements": [
        "No plug-in is removed or reordered.",
        "All changed values are returned to their noted originals unless the user chooses to keep an improvement."
      ],
      "stoppingRules": [
        "Stop the procedure after the bypass and one gentler-setting attempt; more variations invite fatigue and bias."
      ],
      "contraindications": [
        "If no compressor is in use, this procedure is not applicable and is skipped without counting for or against any cause."
      ],
      "knownFailureModes": [
        "Loudness bias mimics improvement or masks it.",
        "The user bypasses the wrong slot; the navigation card must be shown on request."
      ],
      "nonDSPAlternativeProcedureIDs": [
        "tutor.vocal.microphone-position-experiment.v1",
        "tutor.vocal.performance-openness-experiment.v1"
      ],
      "sourceReferences": [
        {
          "sourceIdentity": "Apple Logic Pro Effects User Guide",
          "relevantSection": "Compressor overview and controls",
          "provenanceClass": "appleDocumentedBehavior"
        },
        {
          "sourceIdentity": "iZotope Mixing Guide: Principles, Tips, and Techniques",
          "relevantSection": "Vocal dynamics and level-matched comparison practice",
          "provenanceClass": "professionalPracticeHeuristic"
        },
        {
          "sourceIdentity": "TrackSmith G2 Logic-native bounded profiles",
          "relevantSection": "logic-12.3-compressor-production-profile-48k-2026-07-27 (bounded static-curve and mode evidence; not a musical-preference claim)",
          "provenanceClass": "directLogicEmpiricalEvidence"
        }
      ],
      "empiricalRunIDs": ["logic-12.3-compressor-production-profile-48k-2026-07-27"],
      "subjectiveListeningBoundary": "Whether compression 'emphasizes' the reported quality is a listening judgment. The bounded empirical profile characterizes level behavior on test material only.",
      "grantsExecutionAuthority": false
    },
    {
      "id": "tutor.vocal.channel-eq-resonance-search.v1",
      "version": "1.0",
      "logicVersionScope": "logic-pro-12.3",
      "supportedSourceTypes": ["vocal", "vocalBus"],
      "supportedIssues": ["nasalOrHonky", "congested", "boxy", "muddy", "harsh"],
      "candidateCauses": ["staticSpectralResonance"],
      "prerequisiteQuestions": ["Does the quality seem roughly constant across words, rather than only on specific vowels?"],
      "processorIdentities": ["logic-pro-12.3:channel-eq"],
      "entryStepID": "tutor.vocal.channel-eq-resonance-search.v1.open",
      "steps": [
        {
          "id": "tutor.vocal.channel-eq-resonance-search.v1.open",
          "procedureID": "tutor.vocal.channel-eq-resonance-search.v1",
          "actionKind": "openNativeProcessor",
          "actor": "userManual",
          "title": "Open Channel EQ on the vocal track",
          "instruction": "If the vocal channel strip already has a Channel EQ, click the middle of its slot to open it. Otherwise click an empty Audio FX slot, then choose EQ, then Channel EQ.",
          "substeps": [
            "Select the vocal track.",
            "Open the existing Channel EQ, or add one from an empty Audio FX slot under EQ.",
            "Set a cycle range around one problem phrase."
          ],
          "reason": "We will use one EQ band as a search tool to find where the reported quality lives before deciding whether to correct anything.",
          "technicalExplanation": "Channel EQ offers eight bands including bell shapes with adjustable frequency, gain, and Q. Its analyzer can show the spectrum, but analyzer peaks are evidence, not automatic cut targets.",
          "listenFor": "Nothing yet; this step is setup.",
          "expectedResult": "Channel EQ is open on the vocal and a short phrase loops.",
          "hypothesisWrongSigns": [],
          "preservationChecks": ["If you insert a new Channel EQ, remember it was added for this experiment so you can remove it later if unused."],
          "commonSideEffect": "None yet.",
          "stopCondition": "Stop when the plug-in window is open and the phrase loops.",
          "undoInstruction": "If you added a new Channel EQ and decide against the experiment, click and hold the slot and choose No Plug-in to remove it.",
          "location": {
            "logicVersion": "12.3",
            "workArea": "Inspector channel strip or Mixer; plug-in window",
            "objectScope": "Vocal channel strip Audio FX slot",
            "processorIdentity": "logic-pro-12.3:channel-eq",
            "controlIdentity": "audio-fx-slot",
            "navigationLabels": ["Channel strip", "Audio FX", "EQ", "Channel EQ"],
            "requiredFocusOrSelection": "The vocal track must be selected.",
            "prerequisites": ["A phrase that clearly shows the problem is identified."],
            "verification": "documentary",
            "sourceReferences": [
              "Apple Logic Pro Effects User Guide (Channel EQ overview, pages 112-138)",
              "research/analysis/TRACKSMITH_LOGIC_PRO_12_3_TOOL_ATLAS.md"
            ],
            "lastDirectlyVerified": null
          },
          "parameters": [],
          "supportedFeedback": ["done", "cannotFindControl", "notApplicable"],
          "branches": [
            { "feedback": "done", "nextStepID": "tutor.vocal.channel-eq-resonance-search.v1.band", "effectSummary": "Create the temporary search band." },
            { "feedback": "cannotFindControl", "nextStepID": null, "effectSummary": "Show the navigation card with prerequisites." },
            { "feedback": "notApplicable", "nextStepID": null, "effectSummary": "Skip this procedure without treating it as evidence." }
          ],
          "confidence": 0.6,
          "uncertainty": [],
          "concepts": ["frequency", "resonance"]
        },
        {
          "id": "tutor.vocal.channel-eq-resonance-search.v1.band",
          "procedureID": "tutor.vocal.channel-eq-resonance-search.v1",
          "actionKind": "setControl",
          "actor": "userManual",
          "title": "Set up a temporary exaggerated search boost",
          "instruction": "Click one of the middle bell bands in the Channel EQ display. Set its Q to about 2 and raise its gain to about +6 dB. This boost is deliberately ugly and temporary; it is a magnifying glass, not a mix move.",
          "substeps": [
            "Click a middle bell band in the EQ display.",
            "Set Q near 2.",
            "Raise the band gain to about +6 dB.",
            "Lower your monitor volume a little first."
          ],
          "reason": "Boosting briefly makes the region you sweep through much easier to hear, so you can find where the pinched quality is strongest.",
          "technicalExplanation": "Q describes how narrow the band is: higher Q affects a narrower range of frequencies. A moderate Q near 2 is narrow enough to localize a region and wide enough to hear musical context. The boost exaggerates whatever the band touches; that is the point of a search move, and it must be reduced before any final decision.",
          "listenFor": "Nothing to judge yet. Protect your ears: lower the monitoring level before boosting.",
          "expectedResult": "One band is boosted and ready to sweep.",
          "hypothesisWrongSigns": [],
          "preservationChecks": ["Note that this band was created for searching; it must not remain boosted after the experiment."],
          "commonSideEffect": "Everything the band touches will sound worse while boosted. That is expected and temporary.",
          "stopCondition": "Stop once the band is set; do not leave the boost active outside the sweep.",
          "undoInstruction": "Set the band gain back to 0 dB, or select the band and use its reset, to make the EQ transparent again.",
          "location": {
            "logicVersion": "12.3",
            "workArea": "Channel EQ plug-in window",
            "objectScope": "One bell band of the Channel EQ on the vocal",
            "processorIdentity": "logic-pro-12.3:channel-eq",
            "controlIdentity": "bell-band-gain-frequency-q",
            "navigationLabels": ["Channel EQ", "band display", "Gain", "Frequency", "Q"],
            "requiredFocusOrSelection": "Channel EQ window open with a bell band selected.",
            "prerequisites": ["Monitoring level reduced before boosting."],
            "verification": "documentary",
            "sourceReferences": [
              "Apple Logic Pro Effects User Guide (Channel EQ band controls)",
              "research/analysis/TRACKSMITH_LOGIC_PRO_12_3_TOOL_ATLAS.md"
            ],
            "lastDirectlyVerified": null
          },
          "parameters": [
            {
              "controlIdentity": "channel-eq-band-gain",
              "unit": "decibels",
              "safeStartingValue": 6.0,
              "minimumValue": 4.0,
              "maximumValue": 9.0,
              "enumeratedChoices": [],
              "adjustmentMethod": "setExactValue",
              "sweepDirection": "notApplicable",
              "stepDescription": "A temporary search boost only.",
              "stopCondition": "Never leave this boost active after the sweep.",
              "maximumRecommendedExcursion": 9.0,
              "audibleWarningSigns": ["Distortion or discomfort means the boost or monitoring level is too high."],
              "rollbackValueDescription": "Band gain back to 0 dB."
            },
            {
              "controlIdentity": "channel-eq-band-q",
              "unit": "q",
              "safeStartingValue": 2.0,
              "minimumValue": 1.0,
              "maximumValue": 4.0,
              "enumeratedChoices": [],
              "adjustmentMethod": "setExactValue",
              "sweepDirection": "notApplicable",
              "stepDescription": "Moderate width for searching.",
              "stopCondition": "Keep Q within this range while searching.",
              "maximumRecommendedExcursion": null,
              "audibleWarningSigns": [],
              "rollbackValueDescription": "Band Q back to its default near 0.71, or simply reset the band."
            }
          ],
          "supportedFeedback": ["done", "cannotFindControl", "undo"],
          "branches": [
            { "feedback": "done", "nextStepID": "tutor.vocal.channel-eq-resonance-search.v1.sweep", "effectSummary": "Sweep the boosted band." },
            { "feedback": "cannotFindControl", "nextStepID": null, "effectSummary": "Show the navigation card." },
            { "feedback": "undo", "nextStepID": null, "effectSummary": "Reset the band and leave the procedure." }
          ],
          "confidence": 0.55,
          "uncertainty": ["There is no single universal problem frequency for any voice; the search exists because the region differs per singer, microphone, and room."],
          "concepts": ["qBandwidth", "gain", "frequency", "monitoringBias"]
        },
        {
          "id": "tutor.vocal.channel-eq-resonance-search.v1.sweep",
          "procedureID": "tutor.vocal.channel-eq-resonance-search.v1",
          "actionKind": "sweepControl",
          "actor": "userManual",
          "title": "Sweep slowly and find where the quality is strongest",
          "instruction": "While the phrase loops, drag the boosted band's frequency slowly between about 500 Hz and 4000 Hz. Listen for the region where the specific pinched or honky quality you reported becomes most exaggerated, and leave the band there.",
          "substeps": [
            "Start the band near 1000 Hz.",
            "Sweep slowly downward toward 500 Hz, then upward toward 4000 Hz.",
            "Park the band where the reported quality jumps out most."
          ],
          "reason": "The boosted band exaggerates whatever it touches, so the spot where your specific problem jumps out most is the best candidate region.",
          "technicalExplanation": "Every region will sound worse when boosted; you are not looking for the ugliest spot in general, but for the spot that most resembles the exact quality you reported. Vocal resonances differ per singer, vowel, microphone, and room, which is why this is a search rather than a preset number.",
          "listenFor": "The frequency region where the boost makes the reported pinched quality clearly stronger, not just louder or brighter.",
          "expectedResult": "A candidate frequency region for a restrained correction.",
          "hypothesisWrongSigns": [
            "No region stands out as resembling the reported quality.",
            "The offensive spot moves around depending on the word being sung."
          ],
          "preservationChecks": ["The boost stays temporary; the next step reduces it before any judgment."],
          "commonSideEffect": "Ear fatigue builds quickly while sweeping a boost; take a short break if everything starts sounding the same.",
          "stopCondition": "Stop after two full passes. If nothing stands out by then, report No change rather than forcing a choice.",
          "undoInstruction": "Set the band gain back to 0 dB. The EQ is then transparent again.",
          "location": {
            "logicVersion": "12.3",
            "workArea": "Channel EQ plug-in window",
            "objectScope": "The temporary search band",
            "processorIdentity": "logic-pro-12.3:channel-eq",
            "controlIdentity": "channel-eq-band-frequency",
            "navigationLabels": ["Channel EQ", "band display", "Frequency"],
            "requiredFocusOrSelection": "Channel EQ window open; search band selected.",
            "prerequisites": ["The search boost from the previous step is active."],
            "verification": "documentary",
            "sourceReferences": [
              "Apple Logic Pro Effects User Guide (Channel EQ band controls)",
              "iZotope Mixing Guide (sweep-and-cut practice; labeled professional practice, not a universal rule)"
            ],
            "lastDirectlyVerified": null
          },
          "parameters": [
            {
              "controlIdentity": "channel-eq-band-frequency",
              "unit": "hertz",
              "safeStartingValue": 1000.0,
              "minimumValue": 500.0,
              "maximumValue": 4000.0,
              "enumeratedChoices": [],
              "adjustmentMethod": "slowContinuousSweep",
              "sweepDirection": "bothFromStart",
              "stepDescription": "Slow continuous drag; a full pass should take several seconds.",
              "stopCondition": "Stop where the reported quality is most exaggerated, or after two full passes with no standout.",
              "maximumRecommendedExcursion": 3500.0,
              "audibleWarningSigns": ["Discomfort means the monitoring level is too high for a boosted sweep."],
              "rollbackValueDescription": "Frequency position does not matter once band gain returns to 0 dB."
            }
          ],
          "supportedFeedback": ["done", "noChange", "notSure", "undo"],
          "branches": [
            { "feedback": "done", "nextStepID": "tutor.vocal.channel-eq-resonance-search.v1.cut", "effectSummary": "Reduce the boost to a restrained cut at the found region." },
            { "feedback": "noChange", "nextStepID": null, "effectSummary": "No consistent region: the static-resonance hypothesis weakens. Reset the band; the tutor moves to another cause." },
            { "feedback": "notSure", "nextStepID": null, "effectSummary": "If the spot moves with different words, the problem may be vowel-dependent; a fixed cut is the wrong tool. Reset the band." },
            { "feedback": "undo", "nextStepID": null, "effectSummary": "Reset the band and leave the procedure." }
          ],
          "confidence": 0.5,
          "uncertainty": [
            "A moving or word-dependent standout suggests a time-varying cause that a static EQ cut cannot address well."
          ],
          "concepts": ["resonance", "frequency", "qBandwidth"]
        },
        {
          "id": "tutor.vocal.channel-eq-resonance-search.v1.cut",
          "procedureID": "tutor.vocal.channel-eq-resonance-search.v1",
          "actionKind": "setControl",
          "actor": "userManual",
          "title": "Replace the boost with a restrained cut",
          "instruction": "At the frequency you found, change the band gain from the boost to a small cut: start at -2 dB. Keep Q near 2. Do not chase perfection with a deep cut; small moves first.",
          "substeps": [
            "Set the band gain to -2 dB at the found frequency.",
            "Keep Q between 1.5 and 4.",
            "Replay the whole looped phrase."
          ],
          "reason": "The search move was deliberately exaggerated. The correction should be the smallest cut that makes the quality acceptable, because that band also carries parts of the voice you want to keep.",
          "technicalExplanation": "A cut at the resonant region reduces the pinched emphasis but also removes some presence and vowel color that live in the same range. Deeper or wider cuts remove more of both, which is why restrained moves with listening checks beat aggressive ones.",
          "listenFor": "Less of the pinched quality while the voice keeps its clarity and identity. Warning signs of overdoing it: the voice turns dull or hollow, thins out, consonants soften toward a lisp, or vowels stop sounding like the singer.",
          "expectedResult": "A small cut that reduces the problem with minimal side effects.",
          "hypothesisWrongSigns": ["Even a -6 dB cut leaves the quality unchanged."],
          "preservationChecks": [
            "The voice must keep its recognizable character and clarity.",
            "Do not exceed a -6 dB cut in this procedure."
          ],
          "commonSideEffect": "Cutting too deep makes the vocal dull or hollow.",
          "stopCondition": "Stop at the smallest cut that makes the quality acceptable, and never beyond -6 dB.",
          "undoInstruction": "Set the band gain back to 0 dB to remove the correction entirely.",
          "location": {
            "logicVersion": "12.3",
            "workArea": "Channel EQ plug-in window",
            "objectScope": "The search band, now a correction band",
            "processorIdentity": "logic-pro-12.3:channel-eq",
            "controlIdentity": "channel-eq-band-gain",
            "navigationLabels": ["Channel EQ", "band display", "Gain"],
            "requiredFocusOrSelection": "Channel EQ window open; band selected at the found frequency.",
            "prerequisites": ["A candidate region was found by sweeping."],
            "verification": "documentary",
            "sourceReferences": [
              "Apple Logic Pro Effects User Guide (Channel EQ band controls)",
              "iZotope Mixing Guide (restrained subtractive EQ practice)"
            ],
            "lastDirectlyVerified": null
          },
          "parameters": [
            {
              "controlIdentity": "channel-eq-band-gain",
              "unit": "decibels",
              "safeStartingValue": -2.0,
              "minimumValue": -6.0,
              "maximumValue": -1.0,
              "enumeratedChoices": [],
              "adjustmentMethod": "steppedAdjustment",
              "sweepDirection": "downward",
              "stepDescription": "Deepen in -1 dB steps only if needed.",
              "stopCondition": "Stop at the smallest acceptable cut; hard limit -6 dB.",
              "maximumRecommendedExcursion": 6.0,
              "audibleWarningSigns": ["Dull or hollow tone", "Thinner voice", "Softened consonants approaching a lisp", "Vowels losing the singer's identity"],
              "rollbackValueDescription": "Band gain back to 0 dB."
            },
            {
              "controlIdentity": "channel-eq-band-q",
              "unit": "q",
              "safeStartingValue": 2.0,
              "minimumValue": 1.5,
              "maximumValue": 4.0,
              "enumeratedChoices": [],
              "adjustmentMethod": "steppedAdjustment",
              "sweepDirection": "upward",
              "stepDescription": "Narrow the band slightly if the cut dulls too much around it.",
              "stopCondition": "Stop narrowing when the cut still audibly reduces the problem.",
              "maximumRecommendedExcursion": 2.5,
              "audibleWarningSigns": ["A very narrow deep cut can sound unnatural on sustained vowels."],
              "rollbackValueDescription": "Band Q back to 2."
            }
          ],
          "supportedFeedback": ["done", "worse", "notSure", "cannotFindControl", "undo"],
          "branches": [
            { "feedback": "done", "nextStepID": "tutor.vocal.channel-eq-resonance-search.v1.compare", "effectSummary": "Verify with a level-matched bypass comparison." },
            { "feedback": "worse", "nextStepID": null, "effectSummary": "Reset the band gain to 0 dB; the tutor reconsiders the cause." },
            { "feedback": "notSure", "nextStepID": "tutor.vocal.channel-eq-resonance-search.v1.compare", "effectSummary": "Run the level-matched comparison before judging." },
            { "feedback": "cannotFindControl", "nextStepID": null, "effectSummary": "Show the navigation card." },
            { "feedback": "undo", "nextStepID": null, "effectSummary": "Reset the band gain to 0 dB." }
          ],
          "confidence": 0.5,
          "uncertainty": ["The same band carries desirable vowel color; the right depth is a listening decision."],
          "concepts": ["resonance", "gain", "qBandwidth"]
        },
        {
          "id": "tutor.vocal.channel-eq-resonance-search.v1.compare",
          "procedureID": "tutor.vocal.channel-eq-resonance-search.v1",
          "actionKind": "compareBypass",
          "actor": "userManual",
          "title": "Confirm the cut with a level-matched bypass comparison",
          "instruction": "Toggle the Channel EQ on and off with the power button at the top left of its plug-in window while the phrase loops. A small cut changes loudness very little, so judge the character. If you removed more than about 3 dB in total, raise the EQ's Gain control by about +1 dB before comparing.",
          "substeps": [
            "Loop the phrase.",
            "Toggle the EQ's power button between passes.",
            "Judge the pinched quality, clarity, and the voice's identity."
          ],
          "reason": "A final correction must survive an honest comparison at comparable loudness; otherwise the apparent improvement may be a loudness illusion.",
          "technicalExplanation": "Cuts reduce overall level slightly, and quieter is easily mistaken for worse. The Channel EQ's output Gain control can compensate a larger total cut so the comparison stays about the character rather than the level.",
          "listenFor": "With the EQ on: less pinched, still clear, still recognizably the same voice. With the EQ off: the problem returns.",
          "expectedResult": "Confidence that the small cut genuinely helps, or evidence that it does not.",
          "hypothesisWrongSigns": ["You prefer the EQ off at matched loudness."],
          "preservationChecks": ["If you raised the EQ output Gain for the comparison, keep it proportionate to the total cut and note the value."],
          "commonSideEffect": "None beyond the cut itself.",
          "stopCondition": "Stop after a few toggles; first impressions at matched loudness are the most reliable.",
          "undoInstruction": "Set the band gain to 0 dB and the EQ output Gain back to 0 dB to make the EQ fully transparent.",
          "location": {
            "logicVersion": "12.3",
            "workArea": "Channel EQ plug-in window",
            "objectScope": "Channel EQ power button and output Gain",
            "processorIdentity": "logic-pro-12.3:channel-eq",
            "controlIdentity": "plugin-window-power-and-output-gain",
            "navigationLabels": ["Channel EQ", "plug-in header power button", "Gain"],
            "requiredFocusOrSelection": "Channel EQ window open.",
            "prerequisites": ["A restrained cut is active."],
            "verification": "documentary",
            "sourceReferences": [
              "Apple Logic Pro Effects User Guide (Channel EQ output Gain; plug-in window header)",
              "research/analysis/TRACKSMITH_LOGIC_PRO_12_3_TOOL_ATLAS.md"
            ],
            "lastDirectlyVerified": null
          },
          "parameters": [
            {
              "controlIdentity": "channel-eq-output-gain",
              "unit": "decibels",
              "safeStartingValue": 0.0,
              "minimumValue": 0.0,
              "maximumValue": 2.0,
              "enumeratedChoices": [],
              "adjustmentMethod": "steppedAdjustment",
              "sweepDirection": "upward",
              "stepDescription": "Compensate only what the total cut plausibly removed.",
              "stopCondition": "Stop when on and off feel equally loud.",
              "maximumRecommendedExcursion": 2.0,
              "audibleWarningSigns": ["If on now feels louder than off, the compensation overshot."],
              "rollbackValueDescription": "EQ output Gain back to 0 dB."
            }
          ],
          "supportedFeedback": ["better", "worse", "noChange", "notSure", "undo"],
          "branches": [
            { "feedback": "better", "nextStepID": null, "effectSummary": "Keep the restrained cut; complete the lesson with the principle learned." },
            { "feedback": "worse", "nextStepID": null, "effectSummary": "Reset the band; the static-resonance hypothesis weakens." },
            { "feedback": "noChange", "nextStepID": null, "effectSummary": "Reset the band; move to the next competing cause." },
            { "feedback": "notSure", "nextStepID": null, "effectSummary": "Briefly exaggerate the cut toward -6 dB to hear the direction, then return to the restrained value and judge once more." },
            { "feedback": "undo", "nextStepID": null, "effectSummary": "Reset the band and EQ output Gain." }
          ],
          "confidence": 0.55,
          "uncertainty": ["Ear-based level matching is approximate; TrackSmith cannot measure your monitoring path."],
          "concepts": ["levelMatchedComparison", "monitoringBias", "gain", "resonance"]
        }
      ],
      "preservationRequirements": [
        "The voice's recognizable character and clarity must be preserved; the cut is bounded to -6 dB.",
        "Search boosts are temporary and never remain active after the sweep."
      ],
      "stoppingRules": [
        "Stop at the smallest acceptable cut.",
        "Abandon static EQ when the offensive region moves with different words or vowels."
      ],
      "contraindications": [
        "A strongly vowel-specific or section-specific problem: a fixed cut affects every word all the time and is likely the wrong tool.",
        "A capture that is clipping: fix the overload first."
      ],
      "knownFailureModes": [
        "Choosing the ugliest boosted spot instead of the spot resembling the reported quality.",
        "Leaving the search boost active while judging.",
        "Cutting too deep and trading nasality for dullness."
      ],
      "nonDSPAlternativeProcedureIDs": [
        "tutor.vocal.microphone-position-experiment.v1",
        "tutor.vocal.performance-openness-experiment.v1",
        "tutor.vocal.no-processing-decision.v1"
      ],
      "sourceReferences": [
        {
          "sourceIdentity": "Apple Logic Pro Effects User Guide",
          "relevantSection": "Channel EQ (bands, Q, analyzer, output Gain)",
          "provenanceClass": "appleDocumentedBehavior"
        },
        {
          "sourceIdentity": "iZotope Mixing Guide: Principles, Tips, and Techniques",
          "relevantSection": "Subtractive EQ, sweep-and-cut practice, level-matched comparison",
          "provenanceClass": "professionalPracticeHeuristic"
        },
        {
          "sourceIdentity": "TrackSmith G2 Logic-native bounded profiles",
          "relevantSection": "logic-12.3-channel-eq-production-profile-48k-96k-2026-07-27 (bounded band-behavior evidence on generated fixtures; no vocal-preference claim)",
          "provenanceClass": "directLogicEmpiricalEvidence"
        },
        {
          "sourceIdentity": "Wilson and Fazenda, Perception & Evaluation of Audio Quality in Music Production",
          "relevantSection": "No single descriptor or post-hoc frequency band proves a production adjective",
          "provenanceClass": "peerReviewedResearch"
        }
      ],
      "empiricalRunIDs": ["logic-12.3-channel-eq-production-profile-48k-96k-2026-07-27"],
      "subjectiveListeningBoundary": "Where the search parks and how deep the cut goes are listening decisions. There is no universal nasal frequency, and the bounded empirical profile characterizes filter behavior on fixtures, not vocal aesthetics.",
      "grantsExecutionAuthority": false
    },
    {
      "id": "tutor.vocal.level-matched-bypass-comparison.v1",
      "version": "1.0",
      "logicVersionScope": "logic-pro-12.3",
      "supportedSourceTypes": ["vocal", "vocalBus", "guitar", "fullMix"],
      "supportedIssues": ["nasalOrHonky", "harsh", "dull", "overcompressed", "unclearOrBuried"],
      "candidateCauses": ["monitoringOrLevelBias"],
      "prerequisiteQuestions": [],
      "processorIdentities": [],
      "entryStepID": "tutor.vocal.level-matched-bypass-comparison.v1.compare",
      "steps": [
        {
          "id": "tutor.vocal.level-matched-bypass-comparison.v1.compare",
          "procedureID": "tutor.vocal.level-matched-bypass-comparison.v1",
          "actionKind": "levelMatchComparison",
          "actor": "userManual",
          "title": "Make one honest level-matched comparison",
          "instruction": "Loop one short phrase of 5 to 15 seconds. Compare the two states you are judging, and nudge the channel volume fader so both feel equally loud before you decide anything. Judge the character, never the volume.",
          "substeps": [
            "Set a cycle range around one phrase.",
            "Note the current fader value.",
            "Match loudness by ear between the two states.",
            "Judge the character only."
          ],
          "reason": "Louder nearly always wins a comparison. Matching loudness is the single most reliable habit for honest production decisions.",
          "technicalExplanation": "Small level differences bias preference judgments; comparisons should hold loudness roughly constant so the remaining difference is character. Matching by ear is approximate but removes most of the bias.",
          "listenFor": "Whether the difference you thought you heard survives once loudness is matched.",
          "expectedResult": "A judgment you can trust, or the honest discovery that there is no real difference.",
          "hypothesisWrongSigns": ["Your preference flips depending on listening order."],
          "preservationChecks": ["Return the fader to its noted value afterward."],
          "commonSideEffect": "None when the fader returns to its noted value.",
          "stopCondition": "Stop after a few passes; fatigue makes later judgments less reliable than early ones.",
          "undoInstruction": "Set the channel volume fader back to the value you noted.",
          "location": {
            "logicVersion": "12.3",
            "workArea": "Tracks area and channel strip",
            "objectScope": "Cycle range and channel volume fader",
            "processorIdentity": null,
            "controlIdentity": "channel-volume-fader",
            "navigationLabels": ["Cycle range", "Channel strip", "Volume fader"],
            "requiredFocusOrSelection": "The relevant channel strip must be visible.",
            "prerequisites": [],
            "verification": "documentary",
            "sourceReferences": [
              "Apple Logic Pro User Guide (cycle playback; channel strip volume)"
            ],
            "lastDirectlyVerified": null
          },
          "parameters": [],
          "supportedFeedback": ["better", "worse", "noChange", "done", "notSure"],
          "branches": [
            { "feedback": "better", "nextStepID": null, "effectSummary": "The judged state genuinely helps at matched loudness." },
            { "feedback": "worse", "nextStepID": null, "effectSummary": "The judged state genuinely hurts at matched loudness." },
            { "feedback": "noChange", "nextStepID": null, "effectSummary": "The perceived difference was probably loudness; the tutor reconsiders." },
            { "feedback": "done", "nextStepID": null, "effectSummary": "Comparison complete." },
            { "feedback": "notSure", "nextStepID": null, "effectSummary": "Treat as no change; the tutor simplifies further." }
          ],
          "confidence": 0.65,
          "uncertainty": ["Ear matching is approximate."],
          "concepts": ["levelMatchedComparison", "monitoringBias", "gain"]
        }
      ],
      "preservationRequirements": ["The fader returns to its noted value."],
      "stoppingRules": ["A few passes at most."],
      "contraindications": [],
      "knownFailureModes": ["Order effects; fatigue."],
      "nonDSPAlternativeProcedureIDs": [],
      "sourceReferences": [
        {
          "sourceIdentity": "iZotope Mixing Guide: Principles, Tips, and Techniques",
          "relevantSection": "Level-matched comparison practice",
          "provenanceClass": "professionalPracticeHeuristic"
        },
        {
          "sourceIdentity": "Wilson and Fazenda, Perception & Evaluation of Audio Quality in Music Production",
          "relevantSection": "Perceptual bias and descriptor limits",
          "provenanceClass": "peerReviewedResearch"
        }
      ],
      "empiricalRunIDs": [],
      "subjectiveListeningBoundary": "The comparison outcome is entirely a listening judgment.",
      "grantsExecutionAuthority": false
    },
    {
      "id": "tutor.vocal.microphone-position-experiment.v1",
      "version": "1.0",
      "logicVersionScope": "logic-pro-12.3",
      "supportedSourceTypes": ["vocal"],
      "supportedIssues": ["nasalOrHonky", "congested", "thin", "boomy", "dull", "plosive", "boxy"],
      "candidateCauses": ["microphonePositionOrCapture", "roomOrReflection"],
      "prerequisiteQuestions": ["Can you re-record a short test phrase right now?"],
      "processorIdentities": [],
      "entryStepID": "tutor.vocal.microphone-position-experiment.v1.record",
      "steps": [
        {
          "id": "tutor.vocal.microphone-position-experiment.v1.record",
          "procedureID": "tutor.vocal.microphone-position-experiment.v1",
          "actionKind": "recordAlternateTake",
          "actor": "userManual",
          "title": "Record a short test take with a changed microphone position",
          "instruction": "Create a brand-new audio track and record the same short phrase twice: once at your usual position, once with the microphone a hand-width farther away and aimed slightly below your mouth instead of straight at it. The original take stays untouched on its own track.",
          "substeps": [
            "Create a new audio track with the same input.",
            "Record the phrase at your usual position.",
            "Move back roughly a hand-width and angle the mic slightly downward, then record again."
          ],
          "reason": "Distance and angle change how much nasal and mouth resonance the microphone captures. If position drives the problem, no plug-in is the right fix.",
          "technicalExplanation": "Close placement emphasizes proximity bass and direct mouth and nose radiation; small off-axis angles reduce specific radiation paths. A recording experiment tests the capture hypothesis directly instead of processing around it.",
          "listenFor": "Nothing yet; record first.",
          "expectedResult": "Two short comparable test takes on a new track.",
          "hypothesisWrongSigns": [],
          "preservationChecks": [
            "Record only onto the new track; the original take remains untouched.",
            "Keep both test takes for comparison."
          ],
          "commonSideEffect": "The room contributes more at greater distance; that difference is part of what you are testing.",
          "stopCondition": "Stop after two takes; this is a diagnostic, not a performance session.",
          "undoInstruction": "Mute or delete the new test track when finished. The original recording was never touched.",
          "location": {
            "logicVersion": "12.3",
            "workArea": "Tracks area",
            "objectScope": "A new audio track",
            "processorIdentity": null,
            "controlIdentity": "new-audio-track-record",
            "navigationLabels": ["Track", "New Track", "Audio", "Record enable"],
            "requiredFocusOrSelection": "The new track must be record-enabled with the correct input.",
            "prerequisites": ["The microphone and interface used for the original take are available."],
            "verification": "documentary",
            "sourceReferences": [
              "Apple Logic Pro User Guide (create tracks; record audio)"
            ],
            "lastDirectlyVerified": null
          },
          "parameters": [],
          "supportedFeedback": ["done", "notApplicable", "cannotFindControl"],
          "branches": [
            { "feedback": "done", "nextStepID": "tutor.vocal.microphone-position-experiment.v1.judge", "effectSummary": "Compare the two positions." },
            { "feedback": "notApplicable", "nextStepID": null, "effectSummary": "Re-recording is not possible now; skip without treating this as evidence." },
            { "feedback": "cannotFindControl", "nextStepID": null, "effectSummary": "Show the navigation card." }
          ],
          "confidence": 0.55,
          "uncertainty": ["Performance naturally varies between takes; judge the tonal quality, not the delivery."],
          "concepts": ["sourceVersusProcessing"]
        },
        {
          "id": "tutor.vocal.microphone-position-experiment.v1.judge",
          "procedureID": "tutor.vocal.microphone-position-experiment.v1",
          "actionKind": "reportObservation",
          "actor": "userManual",
          "title": "Compare the two positions at matched loudness",
          "instruction": "Play both test takes back to back at about the same loudness. Ask one question: is the pinched quality clearly weaker in the changed position?",
          "substeps": [
            "Solo the test track.",
            "Play both takes back to back.",
            "Match loudness by ear before judging."
          ],
          "reason": "If position changes the problem, the best fix is at the source, before any processing.",
          "technicalExplanation": "A capture-stage improvement helps every later stage and avoids the side effects of corrective processing entirely.",
          "listenFor": "The pinched or honky quality specifically; ignore differences in delivery between takes.",
          "expectedResult": "Evidence for or against the microphone-position cause.",
          "hypothesisWrongSigns": ["Both positions carry the quality equally."],
          "preservationChecks": ["Unsolo the test track afterward."],
          "commonSideEffect": "None.",
          "stopCondition": "Stop after two or three listens of each take.",
          "undoInstruction": "Mute or delete the test track. The original recording was never touched.",
          "location": {
            "logicVersion": "12.3",
            "workArea": "Tracks area",
            "objectScope": "The test track",
            "processorIdentity": null,
            "controlIdentity": "track-solo",
            "navigationLabels": ["Track header", "Solo"],
            "requiredFocusOrSelection": "The test track must be audible.",
            "prerequisites": ["Two test takes exist."],
            "verification": "documentary",
            "sourceReferences": [
              "Apple Logic Pro User Guide (solo tracks)"
            ],
            "lastDirectlyVerified": null
          },
          "parameters": [],
          "supportedFeedback": ["better", "worse", "noChange", "notSure"],
          "branches": [
            { "feedback": "better", "nextStepID": null, "effectSummary": "Capture position is implicated; consider re-recording the part at the improved position. This may outperform any processing." },
            { "feedback": "worse", "nextStepID": null, "effectSummary": "The changed position is not an improvement; the tutor reconsiders." },
            { "feedback": "noChange", "nextStepID": null, "effectSummary": "Position is probably not the driver; move to the next competing cause." },
            { "feedback": "notSure", "nextStepID": null, "effectSummary": "Repeat once at matched loudness, or treat as no change." }
          ],
          "confidence": 0.5,
          "uncertainty": ["Take-to-take performance variation can mask or mimic a position effect."],
          "concepts": ["sourceVersusProcessing", "levelMatchedComparison"]
        }
      ],
      "preservationRequirements": ["The original take is never recorded over or deleted."],
      "stoppingRules": ["Two test takes; a diagnostic only."],
      "contraindications": ["No access to the original recording setup."],
      "knownFailureModes": ["Judging delivery instead of tone."],
      "nonDSPAlternativeProcedureIDs": ["tutor.vocal.performance-openness-experiment.v1"],
      "sourceReferences": [
        {
          "sourceIdentity": "iZotope Mixing Guide: Principles, Tips, and Techniques",
          "relevantSection": "Capture and source-first practice for vocals",
          "provenanceClass": "professionalPracticeHeuristic"
        },
        {
          "sourceIdentity": "Apple Logic Pro User Guide",
          "relevantSection": "Creating tracks and recording audio",
          "provenanceClass": "appleDocumentedBehavior"
        }
      ],
      "empiricalRunIDs": [],
      "subjectiveListeningBoundary": "Position preference is a listening judgment made on your voice, microphone, and room.",
      "grantsExecutionAuthority": false
    },
    {
      "id": "tutor.vocal.performance-openness-experiment.v1",
      "version": "1.0",
      "logicVersionScope": "logic-pro-12.3",
      "supportedSourceTypes": ["vocal"],
      "supportedIssues": ["nasalOrHonky", "congested", "thin"],
      "candidateCauses": ["performanceOrVowelFormation"],
      "prerequisiteQuestions": ["Can you sing a short test phrase right now?"],
      "processorIdentities": [],
      "entryStepID": "tutor.vocal.performance-openness-experiment.v1.record",
      "steps": [
        {
          "id": "tutor.vocal.performance-openness-experiment.v1.record",
          "procedureID": "tutor.vocal.performance-openness-experiment.v1",
          "actionKind": "adjustPerformanceApproach",
          "actor": "userManual",
          "title": "Re-sing the phrase with a more open delivery",
          "instruction": "On a new audio track, record the same phrase twice: once as you normally sing it, once with your jaw slightly more open and the back of your mouth relaxed, as if starting a yawn. Keep everything else the same.",
          "substeps": [
            "Create a new audio track with the same input.",
            "Record the phrase as usual.",
            "Record it again with a slightly more open, relaxed delivery."
          ],
          "reason": "The pinched quality can come from how the sound is formed. If a small change in delivery removes it, no processing is needed at all.",
          "technicalExplanation": "Vowel formation changes which resonances the voice itself produces. A more open jaw and relaxed soft palate shift energy away from the pinched quality at the source, which no static EQ can do as cleanly afterward.",
          "listenFor": "After recording: is the pinched quality clearly weaker in the more open take, while it still sounds like you?",
          "expectedResult": "Direct evidence about the performance hypothesis.",
          "hypothesisWrongSigns": ["Both deliveries carry the quality equally.", "The open delivery no longer sounds like your voice."],
          "preservationChecks": [
            "Record only onto the new track; the original take stays untouched.",
            "The changed delivery must still sound like you; this is an experiment, not a new technique mandate."
          ],
          "commonSideEffect": "An exaggeratedly open delivery can sound unnatural; aim for a small change.",
          "stopCondition": "Stop after two takes.",
          "undoInstruction": "Mute or delete the test track when finished. The original recording was never touched.",
          "location": {
            "logicVersion": "12.3",
            "workArea": "Tracks area",
            "objectScope": "A new audio track",
            "processorIdentity": null,
            "controlIdentity": "new-audio-track-record",
            "navigationLabels": ["Track", "New Track", "Audio", "Record enable"],
            "requiredFocusOrSelection": "The new track must be record-enabled with the correct input.",
            "prerequisites": ["You can sing the phrase now."],
            "verification": "documentary",
            "sourceReferences": [
              "Apple Logic Pro User Guide (create tracks; record audio)"
            ],
            "lastDirectlyVerified": null
          },
          "parameters": [],
          "supportedFeedback": ["better", "worse", "noChange", "notApplicable", "notSure"],
          "branches": [
            { "feedback": "better", "nextStepID": null, "effectSummary": "The performance hypothesis is strengthened; consider re-recording the part with the more open delivery." },
            { "feedback": "worse", "nextStepID": null, "effectSummary": "The changed delivery hurts; the tutor reconsiders other causes." },
            { "feedback": "noChange", "nextStepID": null, "effectSummary": "Delivery is probably not the driver; move to the next competing cause." },
            { "feedback": "notApplicable", "nextStepID": null, "effectSummary": "Singing now is not possible; skip without treating this as evidence." },
            { "feedback": "notSure", "nextStepID": null, "effectSummary": "Compare once more at matched loudness, or treat as no change." }
          ],
          "confidence": 0.5,
          "uncertainty": ["Take-to-take variation can mask the effect; the singer's comfort matters more than any single take."],
          "concepts": ["sourceVersusProcessing"]
        }
      ],
      "preservationRequirements": ["The original take is never recorded over or deleted.", "The singer's natural identity is preserved; this is a diagnostic, not a permanent instruction to change technique."],
      "stoppingRules": ["Two takes; stop immediately if the delivery feels forced."],
      "contraindications": ["The singer cannot record now."],
      "knownFailureModes": ["Over-exaggerating the open delivery until it is no longer representative."],
      "nonDSPAlternativeProcedureIDs": ["tutor.vocal.microphone-position-experiment.v1"],
      "sourceReferences": [
        {
          "sourceIdentity": "iZotope Mixing Guide: Principles, Tips, and Techniques",
          "relevantSection": "Fix-at-source practice before processing",
          "provenanceClass": "professionalPracticeHeuristic"
        }
      ],
      "empiricalRunIDs": [],
      "subjectiveListeningBoundary": "Whether a delivery change helps and still sounds like the singer is entirely a listening judgment.",
      "grantsExecutionAuthority": false
    },
    {
      "id": "tutor.vocal.no-processing-decision.v1",
      "version": "1.0",
      "logicVersionScope": "logic-pro-12.3",
      "supportedSourceTypes": ["vocal", "vocalBus", "guitar", "fullMix"],
      "supportedIssues": ["nasalOrHonky", "congested", "thin", "dull"],
      "candidateCauses": ["unknown"],
      "prerequisiteQuestions": [],
      "processorIdentities": [],
      "entryStepID": "tutor.vocal.no-processing-decision.v1.decide",
      "steps": [
        {
          "id": "tutor.vocal.no-processing-decision.v1.decide",
          "procedureID": "tutor.vocal.no-processing-decision.v1",
          "actionKind": "stopAndPreserve",
          "actor": "userManual",
          "title": "Consider keeping it: character versus defect",
          "instruction": "Play the phrase once more and ask a different question: does this quality actually hurt the song, or is it part of what makes the voice recognizable? Many distinctive voices carry exactly this kind of coloration. Deciding to change nothing is a valid production decision.",
          "substeps": [
            "Play the phrase in the context of the full mix, not solo.",
            "Ask whether a listener would call this a flaw or a signature."
          ],
          "reason": "Experiments so far have not shown a clear improvement. The most professional move can be to stop before processing erases identity.",
          "technicalExplanation": "Corrective processing always trades something away. When no experiment shows a convincing win, the expected value of further processing is negative: you risk dullness and lost identity for an unproven gain.",
          "listenFor": "In the full mix: does the quality still bother you, or does it disappear into the character of the performance?",
          "expectedResult": "A deliberate keep-or-continue decision.",
          "hypothesisWrongSigns": [],
          "preservationChecks": ["Everything remains exactly as it was; nothing is changed in this step."],
          "commonSideEffect": "None. Nothing changes.",
          "stopCondition": "Stop after one or two listens in context.",
          "undoInstruction": "Nothing to undo; nothing was changed.",
          "location": null,
          "parameters": [],
          "supportedFeedback": ["done", "worse"],
          "branches": [
            { "feedback": "done", "nextStepID": null, "effectSummary": "Keep the sound as-is; complete the lesson preserving everything." },
            { "feedback": "worse", "nextStepID": null, "effectSummary": "The quality still genuinely bothers you in context; the tutor records the unresolved limitation honestly." }
          ],
          "confidence": 0.6,
          "uncertainty": ["Taste, genre, and audience expectations are outside what TrackSmith can measure."],
          "concepts": ["sourceVersusProcessing", "monitoringBias"]
        }
      ],
      "preservationRequirements": ["Everything is preserved; this procedure changes nothing."],
      "stoppingRules": ["One or two listens in context."],
      "contraindications": [],
      "knownFailureModes": ["Solo listening exaggerates flaws that vanish in the mix."],
      "nonDSPAlternativeProcedureIDs": [],
      "sourceReferences": [
        {
          "sourceIdentity": "iZotope Mixing Guide: Principles, Tips, and Techniques",
          "relevantSection": "Restraint and context listening",
          "provenanceClass": "professionalPracticeHeuristic"
        }
      ],
      "empiricalRunIDs": [],
      "subjectiveListeningBoundary": "Entirely a listening and taste decision.",
      "grantsExecutionAuthority": false
    },
    {
      "id": "tutor.vocal.deesser-sibilance-check.v1",
      "version": "1.0",
      "logicVersionScope": "logic-pro-12.3",
      "supportedSourceTypes": ["vocal", "vocalBus"],
      "supportedIssues": ["sibilant", "harsh"],
      "candidateCauses": ["staticSpectralResonance", "dynamicsInteraction"],
      "prerequisiteQuestions": ["Is the problem specifically on s, sh, and t sounds rather than on vowels?"],
      "processorIdentities": ["logic-pro-12.3:deesser-2"],
      "entryStepID": "tutor.vocal.deesser-sibilance-check.v1.insert",
      "steps": [
        {
          "id": "tutor.vocal.deesser-sibilance-check.v1.insert",
          "procedureID": "tutor.vocal.deesser-sibilance-check.v1",
          "actionKind": "openNativeProcessor",
          "actor": "userManual",
          "title": "Open DeEsser 2 on the vocal",
          "instruction": "Click an empty Audio FX slot on the vocal channel strip, then choose Dynamics, then DeEsser 2. If one is already inserted, open it instead.",
          "substeps": [
            "Select the vocal track.",
            "Add DeEsser 2 from an empty Audio FX slot under Dynamics, or open the existing one.",
            "Loop a phrase with obvious s sounds."
          ],
          "reason": "A de-esser reduces gain only when consonant-band energy appears, which fits a problem that lives on s-sounds rather than on vowels.",
          "technicalExplanation": "DeEsser 2 detects energy around a chosen frequency and applies bounded reduction only while that energy is present. This is dynamic, unlike a static EQ cut which would also dull every vowel.",
          "listenFor": "Nothing yet; this step is setup.",
          "expectedResult": "DeEsser 2 open on the vocal with a looping sibilant phrase.",
          "hypothesisWrongSigns": [],
          "preservationChecks": ["If you inserted DeEsser 2 for this experiment, remember to remove it if the experiment does not help."],
          "commonSideEffect": "None yet.",
          "stopCondition": "Stop when the window is open and the phrase loops.",
          "undoInstruction": "Click and hold the DeEsser 2 slot and choose No Plug-in to remove it.",
          "location": {
            "logicVersion": "12.3",
            "workArea": "Inspector channel strip or Mixer; plug-in window",
            "objectScope": "Vocal channel strip Audio FX slot",
            "processorIdentity": "logic-pro-12.3:deesser-2",
            "controlIdentity": "audio-fx-slot",
            "navigationLabels": ["Channel strip", "Audio FX", "Dynamics", "DeEsser 2"],
            "requiredFocusOrSelection": "The vocal track must be selected.",
            "prerequisites": [],
            "verification": "documentary",
            "sourceReferences": [
              "Apple Logic Pro Effects User Guide (DeEsser 2 controls)",
              "research/analysis/TRACKSMITH_LOGIC_PRO_12_3_TOOL_ATLAS.md"
            ],
            "lastDirectlyVerified": null
          },
          "parameters": [],
          "supportedFeedback": ["done", "cannotFindControl", "notApplicable"],
          "branches": [
            { "feedback": "done", "nextStepID": "tutor.vocal.deesser-sibilance-check.v1.tune", "effectSummary": "Tune the detector and amount." },
            { "feedback": "cannotFindControl", "nextStepID": null, "effectSummary": "Show the navigation card." },
            { "feedback": "notApplicable", "nextStepID": null, "effectSummary": "Skip without treating this as evidence." }
          ],
          "confidence": 0.55,
          "uncertainty": [],
          "concepts": ["sibilance", "dynamicVersusStaticProcessing"]
        },
        {
          "id": "tutor.vocal.deesser-sibilance-check.v1.tune",
          "procedureID": "tutor.vocal.deesser-sibilance-check.v1",
          "actionKind": "setControl",
          "actor": "userManual",
          "title": "Reduce only the s-sounds, gently",
          "instruction": "Leave the detector Frequency near its default around 7000 Hz to start. Lower the Threshold until the reduction meter moves only on s and sh sounds, then set Max Reduction to about 4 dB. Replay the phrase.",
          "substeps": [
            "Keep Frequency near 7000 Hz initially.",
            "Lower Threshold until reduction happens only on s-sounds.",
            "Set Max Reduction near 4 dB."
          ],
          "reason": "The goal is reducing the sharp consonants just enough that they stop poking out, while vowels and air remain untouched.",
          "technicalExplanation": "Threshold decides when reduction engages; Max Reduction bounds how deep it can go. Too much reduction or too low a detector frequency creates a lisp-like effect because real consonant information is removed.",
          "listenFor": "S-sounds sit naturally in the phrase. Warning signs: a lisp-like softness, dull air, or reduction on vowels.",
          "expectedResult": "S-sounds controlled without dulling the voice.",
          "hypothesisWrongSigns": ["The harshness you hear is not on consonants at all; a de-esser is then the wrong tool."],
          "preservationChecks": ["Air and consonant clarity must remain; reduction should engage only on sibilant events."],
          "commonSideEffect": "Over-reduction produces a lisp-like sound.",
          "stopCondition": "Stop at the smallest Max Reduction that makes s-sounds acceptable; never beyond 8 dB in this procedure.",
          "undoInstruction": "Set Max Reduction to 0 dB, or remove DeEsser 2 from its slot entirely.",
          "location": {
            "logicVersion": "12.3",
            "workArea": "DeEsser 2 plug-in window",
            "objectScope": "DeEsser 2 on the vocal channel strip",
            "processorIdentity": "logic-pro-12.3:deesser-2",
            "controlIdentity": "threshold-frequency-max-reduction",
            "navigationLabels": ["DeEsser 2", "Threshold", "Frequency", "Max Reduction"],
            "requiredFocusOrSelection": "DeEsser 2 window open.",
            "prerequisites": ["A sibilant phrase loops."],
            "verification": "documentary",
            "sourceReferences": [
              "Apple Logic Pro Effects User Guide (DeEsser 2 controls)",
              "TrackSmith G2 bounded profile logic-12.3-deesser-2-production-profile-48k-2026-07-28 (bounded detector and reduction behavior; no intelligibility-preference claim)"
            ],
            "lastDirectlyVerified": null
          },
          "parameters": [
            {
              "controlIdentity": "deesser2-max-reduction",
              "unit": "decibels",
              "safeStartingValue": 4.0,
              "minimumValue": 1.0,
              "maximumValue": 8.0,
              "enumeratedChoices": [],
              "adjustmentMethod": "steppedAdjustment",
              "sweepDirection": "upward",
              "stepDescription": "Increase in 1 dB steps only if s-sounds still poke out.",
              "stopCondition": "Smallest amount that sounds natural; hard limit 8 dB.",
              "maximumRecommendedExcursion": 8.0,
              "audibleWarningSigns": ["Lisp-like softness", "Dull air", "Reduction engaging on vowels"],
              "rollbackValueDescription": "Max Reduction back to 0 dB, or remove the plug-in."
            },
            {
              "controlIdentity": "deesser2-frequency",
              "unit": "hertz",
              "safeStartingValue": 7000.0,
              "minimumValue": 4000.0,
              "maximumValue": 9000.0,
              "enumeratedChoices": [],
              "adjustmentMethod": "steppedAdjustment",
              "sweepDirection": "bothFromStart",
              "stepDescription": "Adjust only if reduction misses the s-sounds or grabs vowels.",
              "stopCondition": "Stop when reduction engages only on sibilant events.",
              "maximumRecommendedExcursion": 3000.0,
              "audibleWarningSigns": ["Reduction on vowels means the detector is too low."],
              "rollbackValueDescription": "Frequency back to the default near 7000 Hz."
            }
          ],
          "supportedFeedback": ["better", "worse", "noChange", "notSure", "cannotFindControl", "undo"],
          "branches": [
            { "feedback": "better", "nextStepID": null, "effectSummary": "Keep the gentle setting; complete with the principle learned." },
            { "feedback": "worse", "nextStepID": null, "effectSummary": "Set Max Reduction to 0 and reconsider; the problem may not be sibilance." },
            { "feedback": "noChange", "nextStepID": null, "effectSummary": "The problem is probably not consonant-band; move on." },
            { "feedback": "notSure", "nextStepID": null, "effectSummary": "Compare with the plug-in bypassed at matched loudness." },
            { "feedback": "cannotFindControl", "nextStepID": null, "effectSummary": "Show the navigation card." },
            { "feedback": "undo", "nextStepID": null, "effectSummary": "Max Reduction to 0 dB or remove the plug-in." }
          ],
          "confidence": 0.5,
          "uncertainty": ["The bounded empirical profile characterizes detector behavior on tones, not vocal intelligibility preference."],
          "concepts": ["sibilance", "threshold", "dynamicVersusStaticProcessing"]
        }
      ],
      "preservationRequirements": ["Air and consonant clarity are preserved; reduction is bounded to 8 dB."],
      "stoppingRules": ["Smallest natural-sounding reduction wins."],
      "contraindications": ["Harshness on vowels rather than consonants."],
      "knownFailureModes": ["Detector frequency too low grabs vowels.", "Excessive reduction creates a lisp."],
      "nonDSPAlternativeProcedureIDs": ["tutor.vocal.microphone-position-experiment.v1"],
      "sourceReferences": [
        {
          "sourceIdentity": "Apple Logic Pro Effects User Guide",
          "relevantSection": "DeEsser 2 controls",
          "provenanceClass": "appleDocumentedBehavior"
        },
        {
          "sourceIdentity": "TrackSmith G2 Logic-native bounded profiles",
          "relevantSection": "logic-12.3-deesser-2-production-profile-48k-2026-07-28",
          "provenanceClass": "directLogicEmpiricalEvidence"
        }
      ],
      "empiricalRunIDs": ["logic-12.3-deesser-2-production-profile-48k-2026-07-28"],
      "subjectiveListeningBoundary": "Intelligibility, air, and lisp risk are listening judgments not covered by the bounded profile.",
      "grantsExecutionAuthority": false
    },
    {
      "id": "tutor.vocal.broad-body-clarity-rebalance.v1",
      "version": "1.0",
      "logicVersionScope": "logic-pro-12.3",
      "supportedSourceTypes": ["vocal", "vocalBus"],
      "supportedIssues": ["thin", "dull", "nasalOrHonky"],
      "candidateCauses": ["staticSpectralResonance", "existingProcessing"],
      "prerequisiteQuestions": ["Did a recent narrow cut leave the vocal slightly thin or dull?"],
      "processorIdentities": ["logic-pro-12.3:channel-eq"],
      "entryStepID": "tutor.vocal.broad-body-clarity-rebalance.v1.shelf",
      "steps": [
        {
          "id": "tutor.vocal.broad-body-clarity-rebalance.v1.shelf",
          "procedureID": "tutor.vocal.broad-body-clarity-rebalance.v1",
          "actionKind": "setControl",
          "actor": "userManual",
          "title": "Restore a little body with one wide gentle boost",
          "instruction": "In the same Channel EQ, select a different bell band, make it wide by setting Q near 0.7, place it between about 150 Hz and 300 Hz, and raise it by +1 dB. Replay the phrase and compare with the band on and off.",
          "substeps": [
            "Select an unused bell band.",
            "Set Q near 0.7 and frequency between 150 Hz and 300 Hz.",
            "Raise gain by +1 dB and compare on and off."
          ],
          "reason": "A narrow corrective cut can leave the voice slightly smaller. One wide, gentle boost in the body region can restore fullness without undoing the correction.",
          "technicalExplanation": "A low-Q band spreads a small gain change across a wide region, which reads as overall body rather than a new resonance. Small wide moves interact less with the earlier narrow cut than re-deepening or shifting it would.",
          "listenFor": "The voice regains fullness without the pinched quality returning and without becoming muddy or boomy.",
          "expectedResult": "A subtle restoration of body after a corrective cut.",
          "hypothesisWrongSigns": ["The pinched quality returns with the boost."],
          "preservationChecks": [
            "The earlier corrective cut stays exactly where it was.",
            "Do not exceed +2 dB on this band."
          ],
          "commonSideEffect": "Too much low-mid boost trades thinness for mud.",
          "stopCondition": "Stop at +1 dB unless clearly insufficient, and never beyond +2 dB.",
          "undoInstruction": "Set this band's gain back to 0 dB; the corrective cut remains untouched.",
          "location": {
            "logicVersion": "12.3",
            "workArea": "Channel EQ plug-in window",
            "objectScope": "A second bell band of the Channel EQ on the vocal",
            "processorIdentity": "logic-pro-12.3:channel-eq",
            "controlIdentity": "bell-band-gain-frequency-q",
            "navigationLabels": ["Channel EQ", "band display", "Gain", "Frequency", "Q"],
            "requiredFocusOrSelection": "Channel EQ window open.",
            "prerequisites": ["A restrained corrective cut from the resonance search is active."],
            "verification": "documentary",
            "sourceReferences": [
              "Apple Logic Pro Effects User Guide (Channel EQ band controls)",
              "iZotope Mixing Guide (broad tonal balancing after narrow correction)"
            ],
            "lastDirectlyVerified": null
          },
          "parameters": [
            {
              "controlIdentity": "channel-eq-band-gain",
              "unit": "decibels",
              "safeStartingValue": 1.0,
              "minimumValue": 0.5,
              "maximumValue": 2.0,
              "enumeratedChoices": [],
              "adjustmentMethod": "steppedAdjustment",
              "sweepDirection": "upward",
              "stepDescription": "Half-dB steps.",
              "stopCondition": "Stop at the smallest boost that restores body; hard limit +2 dB.",
              "maximumRecommendedExcursion": 2.0,
              "audibleWarningSigns": ["Mud or boom building up", "The pinched quality returning"],
              "rollbackValueDescription": "Band gain back to 0 dB."
            },
            {
              "controlIdentity": "channel-eq-band-q",
              "unit": "q",
              "safeStartingValue": 0.7,
              "minimumValue": 0.5,
              "maximumValue": 1.0,
              "enumeratedChoices": [],
              "adjustmentMethod": "setExactValue",
              "sweepDirection": "notApplicable",
              "stepDescription": "Wide band.",
              "stopCondition": "Keep the band wide for this purpose.",
              "maximumRecommendedExcursion": null,
              "audibleWarningSigns": [],
              "rollbackValueDescription": "Reset the band."
            }
          ],
          "supportedFeedback": ["better", "worse", "noChange", "cannotFindControl", "undo"],
          "branches": [
            { "feedback": "better", "nextStepID": null, "effectSummary": "Keep the gentle rebalance; complete the lesson." },
            { "feedback": "worse", "nextStepID": null, "effectSummary": "Reset the band to 0 dB; the correction stands alone." },
            { "feedback": "noChange", "nextStepID": null, "effectSummary": "Reset the band; unnecessary processing is removed." },
            { "feedback": "cannotFindControl", "nextStepID": null, "effectSummary": "Show the navigation card." },
            { "feedback": "undo", "nextStepID": null, "effectSummary": "Reset the band to 0 dB." }
          ],
          "confidence": 0.5,
          "uncertainty": ["Whether the voice needs body back is a taste decision in context."],
          "concepts": ["gain", "qBandwidth", "frequency"]
        }
      ],
      "preservationRequirements": ["The earlier corrective cut is preserved; this band is bounded to +2 dB."],
      "stoppingRules": ["Smallest sufficient boost; +2 dB hard limit."],
      "contraindications": ["No prior corrective cut exists; then this is ordinary tone shaping, not part of this troubleshooting lesson."],
      "knownFailureModes": ["Trading thinness for mud."],
      "nonDSPAlternativeProcedureIDs": [],
      "sourceReferences": [
        {
          "sourceIdentity": "Apple Logic Pro Effects User Guide",
          "relevantSection": "Channel EQ band controls",
          "provenanceClass": "appleDocumentedBehavior"
        },
        {
          "sourceIdentity": "iZotope Mixing Guide: Principles, Tips, and Techniques",
          "relevantSection": "Broad balancing after narrow correction",
          "provenanceClass": "professionalPracticeHeuristic"
        }
      ],
      "empiricalRunIDs": ["logic-12.3-channel-eq-production-profile-48k-96k-2026-07-27"],
      "subjectiveListeningBoundary": "The amount of body a voice needs is a listening and taste judgment.",
      "grantsExecutionAuthority": false
    }
  ]
}

"""#
}
