// Generated by research/scripts/build-production-language-knowledge.py.
// Do not edit by hand; update PRODUCTION_LANGUAGE_ONTOLOGY.json.

public extension AbstractMusicianLanguageKnowledgeCatalog {
    static let trackSmithV1 = AbstractMusicianLanguageKnowledgeCatalog(
        sourceSHA256: "e2d65a4d35ee8583bd48ecc5684423b6bb7e29b732ffe0cb880ebd62efdb35fc",
        ontologyVersion: "2026-07-19.deep-source-2",
        reviewStatus: .primaryRoleResearchDeepReadProductionSensesRemainHeuristic,
        entries: [
            AbstractMusicianLanguageKnowledge(
                identifier: "expensive",
                surfaceForm: "expensive",
                aliases: ["expensive", "more expensive", "premium", "high-end", "luxurious"],
                applicableSourceTypes: Set([.vocal, .vocalBus, .drums, .drumBus, .bass, .guitar, .keyboard, .synth, .fullMix]),
                canonicalCandidateTerms: Set([.polished, .clear, .controlled, .smooth, .intimate]),
                resolutionPolicy: .multipleNamedHypotheses,
                possibleSenses: [
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.vocal, .vocalBus]),
                        interpretation: "May mean an intentional focal hierarchy, controlled distracting events, stable audibility, and detailed intimacy while retaining breath and performance identity.",
                        supportingEvidenceCategories: ["event-conditioned harshness or sibilance", "level consistency", "spectral balance", "current breath and air evidence"],
                        contradictoryEvidence: ["The vocal may already be over-controlled or over-bright.", "Audible capture texture may be identity-bearing rather than a defect."],
                        candidateStrategyCategories: Set([.subtractiveEQ, .dynamicEQOrDeEsser, .gentleCompression, .preserveWithoutProcessing, .listeningComparison]),
                        unsupportedOrNonDSPConsiderations: ["comp choice", "tuning and detailed editing", "performance selection", "recording-chain quality"]
                    ),
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.drums, .drumBus, .bass, .guitar, .keyboard, .synth]),
                        interpretation: "May mean deliberate tone, envelope, role definition, and an absence of distracting artifacts rather than extra brightness or one fashionable processor.",
                        supportingEvidenceCategories: ["source-specific spectral balance", "transient and sustain evidence", "dynamic consistency", "headroom and safety evidence"],
                        contradictoryEvidence: ["Raw capture, rough edges, or wide dynamics may be artistically intentional.", "The isolated source cannot establish its arrangement role."],
                        candidateStrategyCategories: Set([.subtractiveEQ, .additiveEQ, .gentleCompression, .saturation, .preserveWithoutProcessing, .listeningComparison]),
                        unsupportedOrNonDSPConsiderations: ["arrangement role", "performance", "re-amping or source replacement", "multitrack balance"]
                    ),
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.fullMix]),
                        interpretation: "May mean coherent hierarchy, translation, controlled distractions, and intentional detail; those qualities are relational and cannot be inferred from a mastering curve.",
                        supportingEvidenceCategories: ["loudness-matched tonal balance", "crest and loudness-range evidence", "stereo and mono translation", "peak and true-peak safety"],
                        contradictoryEvidence: ["More density, loudness, brightness, or width can make a mix less distinctive.", "A technically clean mix can still fail the requested emotional goal."],
                        candidateStrategyCategories: Set([.subtractiveEQ, .gentleCompression, .saturation, .stereoWidth, .preserveWithoutProcessing, .listeningComparison]),
                        unsupportedOrNonDSPConsiderations: ["multitrack balance", "arrangement", "performance", "delivery-specific approval"]
                    ),
                ],
                preservationRisks: ["generic polish", "over-brightening", "over-compression", "lost breath or performance identity", "mistaking loudness for quality"],
                provenanceReferences: ["arxiv-2309-03404", "arxiv-2202-08898", "arxiv-2602-12301", "pjc-lukas-001", "TRACKSMITH_PRODUCTION_INTENT_CORPUS_V1"],
                confidence: 0.46,
                prohibitedMapping: "No fixed premium vocal chain, mastering chain, EQ curve, loudness target, or processor stack."
            ),
            AbstractMusicianLanguageKnowledge(
                identifier: "bedroom-recorded",
                surfaceForm: "bedroom-recorded",
                aliases: ["bedroom-recorded", "bedroom recorded", "home-recorded", "home recorded", "demo-like", "sounds like a demo"],
                applicableSourceTypes: Set([.vocal, .vocalBus, .drums, .drumBus, .bass, .guitar, .keyboard, .synth, .fullMix]),
                canonicalCandidateTerms: Set([.polished, .clear, .raw, .intimate, .controlled]),
                resolutionPolicy: .multipleNamedHypotheses,
                possibleSenses: [
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.vocal, .vocalBus, .guitar, .keyboard, .synth]),
                        interpretation: "May report distracting room coloration, noise, resonances, uneven level, or edit artifacts, but it may also describe a valued close and place-specific aesthetic.",
                        supportingEvidenceCategories: ["spectral concentration", "dynamic consistency", "event-conditioned defects", "source-aware proximity or low-mid evidence"],
                        contradictoryEvidence: ["The available analysis does not directly identify room reflections or microphone prestige.", "Environmental texture may support intimacy and authorship."],
                        candidateStrategyCategories: Set([.subtractiveEQ, .dynamicEQOrDeEsser, .gentleCompression, .preserveWithoutProcessing, .listeningComparison]),
                        unsupportedOrNonDSPConsiderations: ["denoising", "dereverberation", "comping", "re-recording", "room and microphone choice"]
                    ),
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.drums, .drumBus, .bass, .fullMix]),
                        interpretation: "May mean uncontrolled capture, small spatial perspective, weak hierarchy, or insufficient translation; each implies a different remedy and some are multitrack or recording problems.",
                        supportingEvidenceCategories: ["tonal distribution", "crest and sustain", "stereo behavior", "loudness-matched translation checks"],
                        contradictoryEvidence: ["Lo-fi, narrow, noisy, or room-heavy production may be deliberate.", "A stereo mix cannot expose which source or recording decision caused the impression."],
                        candidateStrategyCategories: Set([.subtractiveEQ, .gentleCompression, .transientPreservingCompression, .stereoWidth, .preserveWithoutProcessing, .listeningComparison]),
                        unsupportedOrNonDSPConsiderations: ["multitrack rebalance", "room replacement", "recording repair", "arrangement density"]
                    ),
                ],
                preservationRisks: ["sanitizing identity-bearing room or noise", "making the source generic", "removing intimacy", "solving a performance or capture problem with broad DSP"],
                provenanceReferences: ["pjc-zach-holmes-001", "pjc-lukas-001", "arxiv-2309-03404", "TRACKSMITH_PRODUCTION_INTENT_CORPUS_V1"],
                confidence: 0.52,
                prohibitedMapping: "Do not infer noise removal, dereverberation, brightness, or a generic professionalizing chain from this phrase."
            ),
            AbstractMusicianLanguageKnowledge(
                identifier: "vulnerable",
                surfaceForm: "vulnerable",
                aliases: ["vulnerable", "more vulnerable", "fragile", "exposed", "emotionally exposed"],
                applicableSourceTypes: Set([.vocal, .vocalBus, .guitar, .keyboard, .synth, .fullMix]),
                canonicalCandidateTerms: Set([.intimate, .raw, .dynamic, .airy, .soft]),
                resolutionPolicy: .clarificationWhenMaterial,
                possibleSenses: [
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.vocal, .vocalBus]),
                        interpretation: "Usually describes performance exposure, close perspective, retained breath and microdynamics, sparse support, or limited corrective polish rather than one timbral target.",
                        supportingEvidenceCategories: ["dynamic contour", "breath and air evidence", "proximity evidence", "current processing density"],
                        contradictoryEvidence: ["A quieter or breathier vocal is not automatically more emotionally vulnerable.", "The decisive evidence may be performance and lyrics, which TrackSmith cannot infer from descriptors alone."],
                        candidateStrategyCategories: Set([.preserveWithoutProcessing, .gentleCompression, .subtractiveEQ, .listeningComparison, .clarification]),
                        unsupportedOrNonDSPConsiderations: ["performance selection", "comping", "arrangement density", "lyric and narrative context"]
                    ),
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.guitar, .keyboard, .synth, .fullMix]),
                        interpretation: "May describe sparse arrangement, fragile dynamics, exposed imperfections, or a contrast against denser sections; the primary solution may be structural rather than signal processing.",
                        supportingEvidenceCategories: ["macro-dynamic evidence", "crest behavior", "stereo and depth evidence"],
                        contradictoryEvidence: ["More dynamic range or less processing does not prove emotional vulnerability.", "Single-source audio does not reveal arrangement contrast."],
                        candidateStrategyCategories: Set([.preserveWithoutProcessing, .gentleCompression, .listeningComparison, .clarification]),
                        unsupportedOrNonDSPConsiderations: ["arrangement", "performance", "section contrast", "orchestration"]
                    ),
                ],
                preservationRisks: ["over-compression", "noise removal that erases place", "breath removal", "mistaking quietness for emotion", "cosmetic DSP on an arrangement request"],
                provenanceReferences: ["pjc-zach-holmes-001", "pjc-lukas-001", "arxiv-2602-17769", "TRACKSMITH_PRODUCTION_INTENT_CORPUS_V1"],
                confidence: 0.43,
                prohibitedMapping: "No fixed dry-vocal, breath-boost, reduced-compression, or sparse-EQ recipe."
            ),
            AbstractMusicianLanguageKnowledge(
                identifier: "alive",
                surfaceForm: "alive",
                aliases: ["alive", "more alive", "give it life", "more life", "livelier"],
                applicableSourceTypes: Set([.vocal, .vocalBus, .drums, .drumBus, .bass, .guitar, .keyboard, .synth, .fullMix]),
                canonicalCandidateTerms: Set([.energetic, .dynamic, .punchy, .raw, .forward]),
                resolutionPolicy: .multipleNamedHypotheses,
                possibleSenses: [
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.drums, .drumBus, .bass]),
                        interpretation: "May mean stronger groove, transient-to-body contrast, dynamic motion, or harmonic audibility rather than simply more level.",
                        supportingEvidenceCategories: ["transient strength", "onset density", "crest and sustain", "dynamic consistency"],
                        contradictoryEvidence: ["More transient peak or saturation can sound smaller, harsher, or less groovy.", "Groove cannot be reduced to onset density."],
                        candidateStrategyCategories: Set([.transientPreservingCompression, .parallelCompression, .saturation, .preserveWithoutProcessing, .listeningComparison]),
                        unsupportedOrNonDSPConsiderations: ["performance timing", "sample or take choice", "kick-bass relationship outside the current source"]
                    ),
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.vocal, .vocalBus, .guitar, .keyboard, .synth]),
                        interpretation: "May mean present articulation, retained microdynamics, movement, or expressive imperfection; the correct dimension depends on musical role.",
                        supportingEvidenceCategories: ["dynamic envelope", "spectral motion", "transient evidence", "current processing density"],
                        contradictoryEvidence: ["Brightness and loudness can be mistaken for life.", "Modulation or distortion may conflict with a stable focal role."],
                        candidateStrategyCategories: Set([.transientPreservingCompression, .saturation, .additiveEQ, .preserveWithoutProcessing, .listeningComparison]),
                        unsupportedOrNonDSPConsiderations: ["performance", "automation", "MIDI or articulation editing", "arrangement interaction"]
                    ),
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.fullMix]),
                        interpretation: "May mean section contrast, rhythmic motion, focal changes, or preserved dynamics; a static master-bus move may not address it.",
                        supportingEvidenceCategories: ["short-term loudness trajectory", "loudness range", "crest behavior", "tonal and stereo change over time"],
                        contradictoryEvidence: ["A high LRA or crest factor can still feel emotionally static.", "Extra loudness is a confound rather than proof of life."],
                        candidateStrategyCategories: Set([.transientPreservingCompression, .parallelCompression, .saturation, .preserveWithoutProcessing, .listeningComparison, .clarification]),
                        unsupportedOrNonDSPConsiderations: ["section automation", "arrangement", "performance", "multitrack balance"]
                    ),
                ],
                preservationRisks: ["loudness substitution", "harshness", "flattened groove", "exaggerated transients", "unwanted modulation or distortion"],
                provenanceReferences: ["arxiv-2602-17769", "pjc-rhcp-004", "TRACKSMITH_PRODUCTION_INTENT_CORPUS_V1"],
                confidence: 0.47,
                prohibitedMapping: "Do not equate alive with louder, brighter, more compressed, more saturated, or higher crest factor."
            ),
            AbstractMusicianLanguageKnowledge(
                identifier: "emotionally-boring",
                surfaceForm: "emotionally boring",
                aliases: ["emotionally boring", "boring", "lifeless", "emotionless", "flat emotionally", "bland"],
                applicableSourceTypes: Set([.vocal, .vocalBus, .drums, .drumBus, .bass, .guitar, .keyboard, .synth, .fullMix]),
                canonicalCandidateTerms: Set([.energetic, .dynamic, .intimate, .aggressive, .raw]),
                resolutionPolicy: .clarificationWhenMaterial,
                possibleSenses: [
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.vocal, .vocalBus, .guitar, .keyboard, .synth]),
                        interpretation: "May concern performance contour, focal hierarchy, timbral motion, depth, or excessive correction; the emotional diagnosis is not a measured acoustic fact.",
                        supportingEvidenceCategories: ["dynamic trajectory", "spectral motion", "transient and sustain variation", "current processing density"],
                        contradictoryEvidence: ["A spectrally or dynamically static source can be musically compelling.", "TrackSmith cannot observe lyric meaning, intention, or the missing arrangement context from an isolated insert."],
                        candidateStrategyCategories: Set([.preserveWithoutProcessing, .transientPreservingCompression, .saturation, .listeningComparison, .clarification]),
                        unsupportedOrNonDSPConsiderations: ["performance", "composition", "arrangement", "automation and musical phrasing"]
                    ),
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.drums, .drumBus, .bass, .fullMix]),
                        interpretation: "May mean insufficient groove, section contrast, density change, spatial movement, or focal development; several of these are outside single-insert authority.",
                        supportingEvidenceCategories: ["short-term loudness movement", "crest and sustain", "onset density", "stereo trajectory"],
                        contradictoryEvidence: ["More compression, saturation, or width can create excitement only by loudness or novelty.", "Objective motion metrics do not establish emotional engagement."],
                        candidateStrategyCategories: Set([.parallelCompression, .transientPreservingCompression, .saturation, .stereoWidth, .preserveWithoutProcessing, .clarification, .listeningComparison]),
                        unsupportedOrNonDSPConsiderations: ["arrangement", "performance", "section automation", "multitrack hierarchy"]
                    ),
                ],
                preservationRisks: ["unnecessary processing", "novelty effects that distract from the song", "loudness bias", "destroyed restraint or negative space"],
                provenanceReferences: ["arxiv-2602-17769", "arxiv-2309-03404", "TRACKSMITH_PRODUCTION_INTENT_CORPUS_V1"],
                confidence: 0.33,
                prohibitedMapping: "No excitement preset; do not claim that any metric or effect makes music emotionally engaging."
            ),
            AbstractMusicianLanguageKnowledge(
                identifier: "glued",
                surfaceForm: "glued",
                aliases: ["glued", "more glued", "glue", "cohesive", "more cohesive", "hang together"],
                applicableSourceTypes: Set([.vocalBus, .drumBus, .fullMix]),
                canonicalCandidateTerms: Set([.controlled, .smooth, .dynamic, .punchy, .polished]),
                resolutionPolicy: .multipleNamedHypotheses,
                possibleSenses: [
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.vocalBus, .drumBus, .fullMix]),
                        interpretation: "May mean shared dynamic motion, tonal compatibility, ambience continuity, harmonic density, or simply a clearer hierarchy; bus compression is one option rather than the definition.",
                        supportingEvidenceCategories: ["crest and loudness movement", "transient and sustain preservation", "tonal distribution", "stereo coherence"],
                        contradictoryEvidence: ["Compression may reduce groove, kick punch, or section contrast.", "An isolated bus cannot establish whether balance or arrangement is the real source of disunity."],
                        candidateStrategyCategories: Set([.gentleCompression, .parallelCompression, .subtractiveEQ, .saturation, .preserveWithoutProcessing, .listeningComparison]),
                        unsupportedOrNonDSPConsiderations: ["multitrack balance", "shared ambience", "arrangement", "timing relationship"]
                    ),
                ],
                preservationRisks: ["lost groove", "reduced kick punch", "pumping", "flattened section contrast", "loudness bias"],
                provenanceReferences: ["pjc-rhcp-004", "giannoulis-2012-digital-dynamic-range-compressor-design", "arxiv-2309-03404", "TRACKSMITH_PRODUCTION_INTENT_CORPUS_V1"],
                confidence: 0.58,
                prohibitedMapping: "Do not equate glue with one bus-compressor model, setting, gain-reduction amount, or wet/dry ratio."
            ),
            AbstractMusicianLanguageKnowledge(
                identifier: "small",
                surfaceForm: "small",
                aliases: ["small", "smaller", "tiny", "undersized", "feels little"],
                applicableSourceTypes: Set([.vocal, .vocalBus, .drums, .drumBus, .bass, .guitar, .keyboard, .synth, .fullMix]),
                canonicalCandidateTerms: Set([.forward, .punchy, .lowEndWeight, .wide, .intimate]),
                resolutionPolicy: .clarificationWhenMaterial,
                possibleSenses: [
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.vocal, .vocalBus, .guitar, .keyboard, .synth]),
                        interpretation: "May mean low focal level, thin spectral balance, distant depth, narrow image, weak transient definition, or insufficient arrangement role.",
                        supportingEvidenceCategories: ["spectral balance", "crest and envelope", "stereo behavior", "current depth-related evidence"],
                        contradictoryEvidence: ["A narrow or dry source can feel large when it owns the center and level hierarchy.", "Isolated-source measurements cannot establish relative size in the arrangement."],
                        candidateStrategyCategories: Set([.additiveEQ, .transientPreservingCompression, .stereoWidth, .saturation, .listeningComparison, .clarification]),
                        unsupportedOrNonDSPConsiderations: ["relative level", "arrangement", "layering or double-tracking", "ambience design"]
                    ),
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.drums, .drumBus, .bass, .fullMix]),
                        interpretation: "May mean weak impact, insufficient body, narrowness, limited depth, or inadequate macro contrast; those senses have different and sometimes opposing remedies.",
                        supportingEvidenceCategories: ["low-frequency balance", "transient-to-sustain behavior", "stereo and mono behavior", "short-term loudness trajectory"],
                        contradictoryEvidence: ["More low end, width, density, or loudness can each reduce clarity and headroom.", "Small may be an intended intimate scale."],
                        candidateStrategyCategories: Set([.transientPreservingCompression, .parallelCompression, .additiveEQ, .stereoWidth, .saturation, .listeningComparison, .clarification]),
                        unsupportedOrNonDSPConsiderations: ["multitrack hierarchy", "arrangement density", "room or ambience", "sample or performance choice"]
                    ),
                ],
                preservationRisks: ["loudness substitution", "boomy low end", "phasey width", "lost intimacy", "flattened transients"],
                provenanceReferences: ["arxiv-2602-17769", "arxiv-2602-12301", "TRACKSMITH_PRODUCTION_INTENT_CORPUS_V1"],
                confidence: 0.37,
                prohibitedMapping: "Do not equate size with level, bass boost, width, compression, reverb, or saturation without resolving the intended dimension."
            ),
            AbstractMusicianLanguageKnowledge(
                identifier: "bigger",
                surfaceForm: "bigger",
                aliases: ["bigger", "make it big", "huge", "massive", "larger", "larger than life"],
                applicableSourceTypes: Set([.vocal, .vocalBus, .drums, .drumBus, .bass, .guitar, .keyboard, .synth, .fullMix]),
                canonicalCandidateTerms: Set([.lowEndWeight, .wide, .forward, .punchy, .controlled]),
                resolutionPolicy: .clarificationWhenMaterial,
                possibleSenses: [
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.vocal, .vocalBus, .guitar, .keyboard, .synth]),
                        interpretation: "May request greater focal scale through level, body, density, width, depth contrast, or layering; several are relational or unsupported by a single inserted AU.",
                        supportingEvidenceCategories: ["spectral body", "dynamic envelope", "stereo behavior", "peak and headroom evidence"],
                        contradictoryEvidence: ["More reverb can make a source feel farther away.", "More width can weaken the center and mono sum.", "More compression can make transients feel smaller."],
                        candidateStrategyCategories: Set([.additiveEQ, .parallelCompression, .saturation, .stereoWidth, .listeningComparison, .clarification]),
                        unsupportedOrNonDSPConsiderations: ["relative level", "layering", "double-tracking", "arrangement", "ambience"]
                    ),
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.drums, .drumBus, .bass, .fullMix]),
                        interpretation: "May mean more physical low-frequency weight, impact, density, spatial scale, or macro contrast; a safer candidate set keeps these meanings separate.",
                        supportingEvidenceCategories: ["low-end distribution", "crest and sustain", "stereo and mono translation", "short-term loudness and headroom"],
                        contradictoryEvidence: ["Huge can describe the current state rather than the desired direction.", "Loudness-mismatched candidates will bias size judgments."],
                        candidateStrategyCategories: Set([.additiveEQ, .transientPreservingCompression, .parallelCompression, .saturation, .stereoWidth, .listeningComparison, .clarification]),
                        unsupportedOrNonDSPConsiderations: ["kick-bass relationship", "multitrack balance", "arrangement", "room and ambience"]
                    ),
                ],
                preservationRisks: ["lost headroom", "masking", "mono loss", "distant depth", "loudness bias", "role competition"],
                provenanceReferences: ["arxiv-2602-12301", "arxiv-2309-03404", "TRACKSMITH_PRODUCTION_INTENT_CORPUS_V1"],
                confidence: 0.36,
                prohibitedMapping: "No universal bigger preset and no assumption that the word is desired rather than descriptive."
            ),
            AbstractMusicianLanguageKnowledge(
                identifier: "three-dimensional",
                surfaceForm: "three-dimensional",
                aliases: ["three-dimensional", "three dimensional", "3d", "more dimensional", "depth and dimension", "immersive"],
                applicableSourceTypes: Set([.vocalBus, .drumBus, .guitar, .keyboard, .synth, .fullMix]),
                canonicalCandidateTerms: Set([.wide, .clear, .intimate, .distant, .forward, .monoCompatibility]),
                resolutionPolicy: .multipleNamedHypotheses,
                possibleSenses: [
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.vocalBus, .drumBus, .guitar, .keyboard, .synth]),
                        interpretation: "May mean stereo extent, front-back depth, direct-versus-ambient contrast, spectral separation, or time-varying movement; width is only one dimension.",
                        supportingEvidenceCategories: ["side-energy share", "mono-sum behavior", "low-band side energy", "spectral density and envelope"],
                        contradictoryEvidence: ["Decorrelated width can sound phasey or collapse in mono.", "The current source may not contain the independent layers needed for convincing spatial scale."],
                        candidateStrategyCategories: Set([.stereoWidth, .subtractiveEQ, .preserveWithoutProcessing, .listeningComparison, .clarification]),
                        unsupportedOrNonDSPConsiderations: ["ambience and delay design", "independent layers", "panning", "multitrack depth hierarchy"]
                    ),
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.fullMix]),
                        interpretation: "May mean a coherent depth hierarchy and contrasting center, sides, direct sound, and ambience across sources rather than maximal stereo width.",
                        supportingEvidenceCategories: ["frequency-dependent stereo behavior", "mono translation", "tonal balance", "section-wise spatial change"],
                        contradictoryEvidence: ["A stereo master cannot reconstruct missing independent depth relationships.", "Global widening may damage focal stability and low-end mono compatibility."],
                        candidateStrategyCategories: Set([.stereoWidth, .subtractiveEQ, .preserveWithoutProcessing, .listeningComparison, .clarification]),
                        unsupportedOrNonDSPConsiderations: ["multitrack panning", "send ambience", "front-back source hierarchy", "arrangement"]
                    ),
                ],
                preservationRisks: ["mono collapse", "diffuse focal source", "low-end instability", "phase artifacts", "mistaking width for depth"],
                provenanceReferences: ["arxiv-2309-03404", "arxiv-2602-17769", "TRACKSMITH_PRODUCTION_INTENT_CORPUS_V1"],
                confidence: 0.41,
                prohibitedMapping: "Do not equate three-dimensional with one stereo-width value, Haas delay, reverb preset, or side boost."
            ),
            AbstractMusicianLanguageKnowledge(
                identifier: "human",
                surfaceForm: "human",
                aliases: ["human", "more human", "keep it human", "organic", "natural", "not robotic"],
                applicableSourceTypes: Set([.vocal, .vocalBus, .drums, .drumBus, .bass, .guitar, .keyboard, .synth, .fullMix]),
                canonicalCandidateTerms: Set([.raw, .dynamic, .intimate, .soft, .controlled]),
                resolutionPolicy: .clarificationWhenMaterial,
                possibleSenses: [
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.vocal, .vocalBus, .drums, .drumBus, .bass, .guitar, .keyboard, .synth]),
                        interpretation: "May ask to preserve performance timing, pitch nuance, microdynamics, breath, touch, noise, or non-repeating variation; those are not interchangeable.",
                        supportingEvidenceCategories: ["dynamic variation", "transient and sustain variation", "source-specific articulation evidence", "current processing density"],
                        contradictoryEvidence: ["Random variation is not equivalent to human performance.", "Tight timing or consistent dynamics can still be an intentional human performance."],
                        candidateStrategyCategories: Set([.preserveWithoutProcessing, .gentleCompression, .transientPreservingCompression, .listeningComparison, .clarification]),
                        unsupportedOrNonDSPConsiderations: ["timing edits", "pitch edits", "performance selection", "MIDI humanization", "comping"]
                    ),
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.fullMix]),
                        interpretation: "May mean retaining expressive imperfections, macro dynamics, ensemble relationships, or a recognizable rough-mix identity.",
                        supportingEvidenceCategories: ["loudness range", "crest behavior", "section trajectory", "current graph density"],
                        contradictoryEvidence: ["Higher loudness range does not prove humanity.", "The stereo mix does not expose take, edit, or timing history."],
                        candidateStrategyCategories: Set([.preserveWithoutProcessing, .gentleCompression, .listeningComparison, .clarification]),
                        unsupportedOrNonDSPConsiderations: ["multitrack performance relationships", "edit history", "arrangement", "rough-mix comparison"]
                    ),
                ],
                preservationRisks: ["over-tuning", "over-quantization", "over-compression", "noise removal that erases place", "adding fake randomness"],
                provenanceReferences: ["pjc-zach-holmes-001", "pjc-lukas-001", "arxiv-2602-17769", "TRACKSMITH_PRODUCTION_INTENT_CORPUS_V1"],
                confidence: 0.44,
                prohibitedMapping: "No randomization, reduced processing amount, saturation, or imperfection preset can be assumed to create humanity."
            ),
            AbstractMusicianLanguageKnowledge(
                identifier: "blurry",
                surfaceForm: "blurry",
                aliases: ["blurry", "blurred", "smeared", "indistinct", "fuzzy in a bad way"],
                applicableSourceTypes: Set([.vocal, .vocalBus, .drums, .drumBus, .bass, .guitar, .keyboard, .synth, .fullMix]),
                canonicalCandidateTerms: Set([.muddy, .clear, .tight, .controlled, .boomy]),
                resolutionPolicy: .multipleNamedHypotheses,
                possibleSenses: [
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.bass, .drums, .drumBus]),
                        interpretation: "May mean excessive low-frequency overlap, long sustain, unstable note or hit level, weak leading definition, or kick-bass interaction.",
                        supportingEvidenceCategories: ["sub and low-mid balance", "transient strength", "sustain behavior", "dynamic consistency"],
                        contradictoryEvidence: ["Sustained or blended low end may be intentional.", "A single source cannot reveal kick-bass timing or masking."],
                        candidateStrategyCategories: Set([.subtractiveEQ, .gentleCompression, .transientPreservingCompression, .preserveWithoutProcessing, .listeningComparison]),
                        unsupportedOrNonDSPConsiderations: ["kick-bass timing", "multitrack masking", "note editing", "source selection"]
                    ),
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.vocal, .vocalBus, .guitar, .keyboard, .synth, .fullMix]),
                        interpretation: "May mean spectral masking, diffuse depth, excessive ambience, smeared transients, or dense arrangement rather than one frequency defect.",
                        supportingEvidenceCategories: ["spectral density and concentration", "transient and sustain", "stereo behavior", "source-specific tonal evidence"],
                        contradictoryEvidence: ["Dense or washed texture may be a chosen aesthetic.", "The inserted AU lacks multitrack masking and ambience-send context."],
                        candidateStrategyCategories: Set([.subtractiveEQ, .transientPreservingCompression, .stereoWidth, .preserveWithoutProcessing, .listeningComparison, .clarification]),
                        unsupportedOrNonDSPConsiderations: ["ambience sends", "arrangement density", "multitrack balance", "source editing"]
                    ),
                ],
                preservationRisks: ["thinness", "lost sustain", "over-separation", "lost intentional wash", "attacking the wrong source"],
                provenanceReferences: ["arxiv-2202-08898", "arxiv-2309-03404", "TRACKSMITH_PRODUCTION_INTENT_CORPUS_V1"],
                confidence: 0.49,
                prohibitedMapping: "Do not equate blurry with one low-mid cut, faster compression, transient boost, or reverb reduction."
            ),
            AbstractMusicianLanguageKnowledge(
                identifier: "painful-when-loud",
                surfaceForm: "hurts when loud",
                aliases: ["hurts when loud", "hurts when I turn it up", "painful", "piercing", "ear-piercing", "fatiguing at volume"],
                applicableSourceTypes: Set([.vocal, .vocalBus, .drums, .drumBus, .guitar, .keyboard, .synth, .fullMix]),
                canonicalCandidateTerms: Set([.harsh, .sibilant, .cymbalHarshness, .bright, .aggressive, .pickAttack]),
                resolutionPolicy: .multipleNamedHypotheses,
                possibleSenses: [
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.vocal, .vocalBus]),
                        interpretation: "May indicate event-specific sibilance, upper-mid harshness, clipping, dense sustained brightness, or a monitoring-level interaction; preserve intelligibility and breath while testing alternatives.",
                        supportingEvidenceCategories: ["sibilance-event evidence", "upper-band energy", "peak and nonfinite safety", "air evidence"],
                        contradictoryEvidence: ["Average brightness cannot locate brief painful events.", "The problem may originate in monitoring, another source, or an upstream nonlinear stage."],
                        candidateStrategyCategories: Set([.dynamicEQOrDeEsser, .subtractiveEQ, .gentleCompression, .preserveWithoutProcessing, .listeningComparison]),
                        unsupportedOrNonDSPConsiderations: ["monitoring calibration", "upstream clipping", "other-source masking or resonance", "event editing"]
                    ),
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.drums, .drumBus]),
                        interpretation: "May indicate cymbal-event harshness, clipped transients, resonant upper mids, or cumulative sustain; the drum attack and cymbal tone require separate constraints.",
                        supportingEvidenceCategories: ["transient high-frequency energy", "cymbal sustain", "crest and peak safety", "spectral concentration"],
                        contradictoryEvidence: ["Broad treble cuts can bury stick and snare definition.", "Static spectrum can miss event-specific pain."],
                        candidateStrategyCategories: Set([.dynamicEQOrDeEsser, .subtractiveEQ, .transientPreservingCompression, .preserveWithoutProcessing, .listeningComparison]),
                        unsupportedOrNonDSPConsiderations: ["cymbal balance", "overhead close-mic relationship", "monitoring calibration"]
                    ),
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.guitar, .keyboard, .synth, .fullMix]),
                        interpretation: "May indicate resonant concentration, distortion intermodulation, aliasing, clipping, or sustained tonal balance rather than a generic lack of warmth.",
                        supportingEvidenceCategories: ["2-5 kHz energy", "third-octave concentration", "peak safety", "spectral density"],
                        contradictoryEvidence: ["Aggressive pick or synth edge may be an explicit preserved trait.", "A stereo mix cannot attribute the painful event to one source."],
                        candidateStrategyCategories: Set([.dynamicEQOrDeEsser, .subtractiveEQ, .gentleCompression, .preserveWithoutProcessing, .listeningComparison]),
                        unsupportedOrNonDSPConsiderations: ["amp or synth patch revision", "monitoring calibration", "multitrack attribution", "upstream nonlinear processing"]
                    ),
                ],
                preservationRisks: ["lost aggression", "buried pick or stick attack", "lost diction or air", "blanket dullness", "false attribution"],
                provenanceReferences: ["arxiv-2202-08898", "arxiv-2603-16682", "TRACKSMITH_PRODUCTION_INTENT_CORPUS_V1"],
                confidence: 0.57,
                prohibitedMapping: "No universal harsh-frequency notch or high-shelf cut; event timing, source, level, and monitoring remain material."
            ),
            AbstractMusicianLanguageKnowledge(
                identifier: "surround-the-vocal",
                surfaceForm: "surround the vocal",
                aliases: ["surround the vocal", "wrap around the vocal", "sit around the vocal", "make room around the vocal", "outside the vocal"],
                applicableSourceTypes: Set([.guitar, .keyboard, .synth, .fullMix]),
                canonicalCandidateTerms: Set([.wide, .clear, .monoCompatibility, .distant, .forward]),
                resolutionPolicy: .clarificationWhenMaterial,
                possibleSenses: [
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.guitar, .keyboard, .synth]),
                        interpretation: "May request a relational change in width, center occupancy, spectral competition, depth, or level so a vocal remains focal; TrackSmith cannot verify that relation without vocal or mix context.",
                        supportingEvidenceCategories: ["source stereo behavior", "low-band side energy", "spectral density", "mono-sum behavior"],
                        contradictoryEvidence: ["Widening can create mono loss without creating vocal space.", "EQ on the accompaniment may target the wrong band without vocal evidence."],
                        candidateStrategyCategories: Set([.stereoWidth, .subtractiveEQ, .preserveWithoutProcessing, .listeningComparison, .clarification]),
                        unsupportedOrNonDSPConsiderations: ["vocal-accompaniment masking", "panning", "sidechain context", "multitrack level and depth"]
                    ),
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.fullMix]),
                        interpretation: "Describes a multitrack hierarchy inside the stereo mix; a master-bus insert should usually abstain from pretending it can separately move the accompaniment around the vocal.",
                        supportingEvidenceCategories: ["global stereo and mono behavior", "tonal balance", "focal stability under audition"],
                        contradictoryEvidence: ["Master-bus widening or EQ changes every source.", "The vocal identity is not isolated in current analysis."],
                        candidateStrategyCategories: Set([.preserveWithoutProcessing, .clarification, .listeningComparison]),
                        unsupportedOrNonDSPConsiderations: ["multitrack panning", "source-specific EQ", "send ambience", "vocal automation"]
                    ),
                ],
                preservationRisks: ["mono loss", "weak center", "incorrect spectral carving", "altering low-end focus", "hallucinated multitrack authority"],
                provenanceReferences: ["arxiv-2309-03404", "dafx-2011-audio-effects-ontology", "TRACKSMITH_PRODUCTION_INTENT_CORPUS_V1"],
                confidence: 0.51,
                prohibitedMapping: "Do not treat the current inserted source as if TrackSmith can observe or independently edit the vocal and accompaniment."
            ),
            AbstractMusicianLanguageKnowledge(
                identifier: "clean-without-sterilizing",
                surfaceForm: "clean without sterilizing",
                aliases: ["clean it up without sterilizing", "clean without sterilizing", "cleaner but natural", "polish it but keep it human", "clean but not sterile"],
                applicableSourceTypes: Set([.vocal, .vocalBus, .drums, .drumBus, .bass, .guitar, .keyboard, .synth, .fullMix]),
                canonicalCandidateTerms: Set([.clear, .polished, .raw, .dynamic, .intimate]),
                resolutionPolicy: .multipleNamedHypotheses,
                possibleSenses: [
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.vocal, .vocalBus, .drums, .drumBus, .bass, .guitar, .keyboard, .synth]),
                        interpretation: "Requests selective control of distracting defects while explicitly preserving performance, place, dynamics, and source identity; the default null hypothesis is material.",
                        supportingEvidenceCategories: ["source-specific event defects", "dynamic consistency", "spectral concentration", "current raw and intimate evidence"],
                        contradictoryEvidence: ["An apparent defect may be identity-bearing.", "Current metrics may not distinguish capture texture from noise or intentional grit."],
                        candidateStrategyCategories: Set([.subtractiveEQ, .dynamicEQOrDeEsser, .gentleCompression, .preserveWithoutProcessing, .listeningComparison]),
                        unsupportedOrNonDSPConsiderations: ["comping and editing", "denoising", "timing or pitch repair", "recording replacement"]
                    ),
                    AbstractMusicianLanguageSense(
                        sourceTypes: Set([.fullMix]),
                        interpretation: "May request correction of distracting peaks, resonances, imbalance, or translation problems while preserving macro dynamics, rough-mix identity, and intentional texture.",
                        supportingEvidenceCategories: ["peak and true-peak safety", "tonal balance", "loudness range and crest", "stereo and mono translation"],
                        contradictoryEvidence: ["Master-bus cleanup may mask a source-specific problem.", "More uniform tone or dynamics can erase intentional contrast."],
                        candidateStrategyCategories: Set([.subtractiveEQ, .gentleCompression, .preserveWithoutProcessing, .listeningComparison, .clarification]),
                        unsupportedOrNonDSPConsiderations: ["multitrack repair", "arrangement", "source replacement", "delivery approval"]
                    ),
                ],
                preservationRisks: ["sterility", "generic tone", "lost dynamics", "lost ambience or noise identity", "over-correction"],
                provenanceReferences: ["pjc-zach-holmes-001", "pjc-lukas-001", "arxiv-2309-03404", "TRACKSMITH_PRODUCTION_INTENT_CORPUS_V1"],
                confidence: 0.61,
                prohibitedMapping: "Do not infer blanket noise removal, tuning, quantization, compression, or spectral smoothing."
            ),
        ]
    )
}
