// Generated by research/scripts/build-logic-core-effect-priority.py.
// Do not edit by hand; update the source-grounded priority generator.

public enum LogicCoreEffectPriority {
    public static let rankByName: [String: Int] = [
        "Gain": 1,
        "Channel EQ": 2,
        "Compressor": 3,
        "DeEsser 2": 4,
        "Noise Gate": 5,
        "ChromaVerb": 6,
        "Space Designer": 7,
        "Stereo Delay": 8,
        "Tape Delay": 9,
        "ChromaGlow": 10,
        "Overdrive": 11,
        "Limiter": 12,
        "Adaptive Limiter": 13,
        "Loudness Meter": 14,
        "MultiMeter": 15,
        "Direction Mixer": 16,
        "Correlation Meter": 17,
        "Pitch Correction": 18,
        "Enveloper": 19,
        "Linear Phase EQ": 20,
    ]

    public static let evidenceBoundary =
        "CURATED_58_CASE_ROLE_RECURRENCE_NOT_GLOBAL_USAGE_TELEMETRY_OR_FIXED_PROCESSING_ORDER"
}
